#!/usr/bin/env npx tsx
/**
 * Adds vector-search metadata fields to existing corpus entries
 * and appends new law entries.
 * Run: npx tsx scripts/add-metadata.ts
 */

import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const ROOT = join(import.meta.dirname, '..')
const src = JSON.parse(readFileSync(join(ROOT, 'data/regulations.json'), 'utf8'))

// ─── Metadata map for existing entries ───────────────────────────────────────
// Format: { legal_citation, topics, sector_tags, technology_tags, key_obligations }

const META: Record<string, {
  legal_citation: string
  topics: string[]
  sector_tags: string[]
  technology_tags: string[]
  key_obligations: string[]
}> = {
  'us-fed-eo14110-2023': {
    legal_citation: 'Exec. Order No. 14,110, 88 Fed. Reg. 75,191 (Nov. 1, 2023)',
    topics: ['AI safety standards', 'government AI procurement', 'frontier model safety', 'biosecurity AI risks', 'AI in hiring', 'AI risk assessment'],
    sector_tags: ['government_services', 'healthcare', 'employment', 'critical_infrastructure', 'all_sectors'],
    technology_tags: ['large_language_models', 'generative_ai', 'autonomous_systems', 'decision_support_systems'],
    key_obligations: ['Frontier AI developers with training compute above threshold must share safety test results with NIST', 'NIST to develop AI risk management benchmarks and red-teaming standards', 'Federal agencies must conduct AI risk assessments before procurement', 'OMB to issue binding guidance on government AI use and procurement'],
  },
  'us-fed-eo14179-2025': {
    legal_citation: 'Exec. Order No. 14,179, 90 Fed. Reg. 8,741 (Jan. 31, 2025)',
    topics: ['federal AI policy', 'AI innovation', 'deregulation', 'AI competitiveness'],
    sector_tags: ['government_services', 'all_sectors'],
    technology_tags: ['generative_ai', 'autonomous_systems', 'large_language_models'],
    key_obligations: ['Agencies to review and revoke Biden-era AI policies inconsistent with innovation priority', 'OSTP and OSTP to develop AI Action Plan prioritizing US AI dominance', 'Remove regulatory barriers to AI development and deployment'],
  },
  'us-fed-take-it-down-2026': {
    legal_citation: 'S. 146, 119th Cong. (2026)',
    topics: ['non-consensual intimate imagery', 'deepfake pornography', 'content takedown obligations', 'platform accountability', 'child safety online'],
    sector_tags: ['telecommunications', 'entertainment_media', 'consumer'],
    technology_tags: ['deepfake', 'image_synthesis', 'generative_ai', 'voice_cloning'],
    key_obligations: ['Platforms must remove non-consensual intimate imagery (NCII) including AI-generated within 48 hours of valid request', 'Criminal prohibition on publishing NCII', 'FTC to enforce against non-compliant platforms under Section 5'],
  },
  'us-ca-sb53-2025': {
    legal_citation: 'Cal. Gov. Code §§ 11547.4–11547.5; SB 53, 2025–26 Leg. Sess.',
    topics: ['frontier model safety', 'AI safety testing', 'catastrophic risk prevention', 'incident reporting', 'developer obligations'],
    sector_tags: ['all_sectors'],
    technology_tags: ['large_language_models', 'generative_ai', 'autonomous_systems'],
    key_obligations: ['Developers of covered large AI models must conduct pre-deployment safety evaluations', 'Publish safety policy and incident response plan publicly', 'Report critical safety incidents to California AG within 72 hours', 'Implement capability-based safeguards for models above training compute threshold'],
  },
  'us-ca-ab2013-2024': {
    legal_citation: 'Cal. Gov. Code § 11547.6; AB 2013, 2023–24 Leg. Sess.',
    topics: ['training data transparency', 'generative AI disclosure', 'data sourcing', 'personal data in AI training'],
    sector_tags: ['all_sectors'],
    technology_tags: ['generative_ai', 'large_language_models'],
    key_obligations: ['GenAI developers must publicly post training data summary on website', 'Disclosure must include data types, sources, whether personal information was used', 'Disclose whether synthetic data was used in training', 'Update disclosures when model is significantly retrained'],
  },
  'us-ca-sb942-2024': {
    legal_citation: 'Cal. Civ. Code § 3506; SB 942, 2023–24 Leg. Sess.',
    topics: ['AI content watermarking', 'content provenance', 'AI-generated content labeling', 'digital watermarks', 'deepfake detection'],
    sector_tags: ['entertainment_media', 'telecommunications', 'consumer', 'all_sectors'],
    technology_tags: ['generative_ai', 'image_synthesis', 'deepfake', 'large_language_models', 'content_moderation_ai'],
    key_obligations: ['Large AI providers (1M+ monthly users) must embed watermarks in AI-generated images, video, audio', 'Provide free public detection tool for users to verify AI-generated content', 'Maintain manifest of watermarked content', 'Label AI-generated political content prominently'],
  },
  'us-ca-sb243-2025': {
    legal_citation: 'Cal. Bus. & Prof. Code §§ 22944–22944.5; SB 243, 2025–26 Leg. Sess.',
    topics: ['AI companion chatbots', 'chatbot disclosure', 'minor protection', 'mental health AI', 'romantic AI bots'],
    sector_tags: ['consumer', 'healthcare', 'entertainment_media'],
    technology_tags: ['natural_language_processing', 'large_language_models', 'agentic_systems'],
    key_obligations: ['Disclose AI identity when user sincerely asks if interacting with human', 'Prohibit romantic or sexual interactions with minors', 'Implement suicide/self-harm safe messaging protocols', 'Private right of action: $1,000 per violation'],
  },
  'us-ca-ab325-2025': {
    legal_citation: 'Cal. Bus. & Prof. Code §§ 16700–16761 (Cartwright Act amendment); AB 325, 2025–26 Leg. Sess.',
    topics: ['algorithmic pricing', 'price-fixing', 'antitrust AI', 'competitor data sharing', 'rental pricing algorithms'],
    sector_tags: ['financial_services', 'consumer', 'housing', 'all_sectors'],
    technology_tags: ['decision_support_systems', 'predictive_analytics', 'recommendation_systems'],
    key_obligations: ['Prohibition on using common pricing algorithm with competitor data to coordinate prices', 'Cannot coerce competitors into adopting algorithm-recommended prices', 'Private right of action under Cartwright Act; treble damages available'],
  },
  'us-ca-sb361-2025': {
    legal_citation: 'Cal. Bus. & Prof. Code §§ 1798.93.3–1798.93.5; SB 361, 2025–26 Leg. Sess.',
    topics: ['training data consent', 'data broker obligations', 'GenAI training data', 'opt-out rights', 'personal data in AI'],
    sector_tags: ['all_sectors', 'consumer'],
    technology_tags: ['generative_ai', 'large_language_models'],
    key_obligations: ['Data brokers must disclose when consumer data is shared with GenAI developers for training', 'Update privacy disclosures to reflect AI training use', 'Provide opt-out mechanism for GenAI training use of personal data'],
  },
  'us-co-sb205-2024': {
    legal_citation: 'Colo. Rev. Stat. §§ 6-1-1701 to 6-1-1711; SB 24-205',
    topics: ['high-risk AI', 'algorithmic impact assessment', 'algorithmic discrimination', 'consumer notification', 'AI in employment', 'AI in lending', 'AI in housing', 'AI in healthcare', 'AI in insurance'],
    sector_tags: ['employment', 'financial_services', 'housing', 'healthcare', 'education', 'consumer'],
    technology_tags: ['decision_support_systems', 'predictive_analytics', 'computer_vision', 'natural_language_processing'],
    key_obligations: ['Deployers of high-risk AI must use reasonable care to prevent algorithmic discrimination', 'Conduct and document algorithmic impact assessment before deployment', 'Notify consumers when high-risk AI is used in consequential decisions', 'Provide opportunity for consumers to appeal AI-assisted decisions', 'Developers must provide deployers with impact assessment documentation'],
  },
  'us-tx-hb149-2025': {
    legal_citation: 'Tex. Bus. & Com. Code §§ 541.001–541.056 (TRAIGA); HB 149, 89th Leg.',
    topics: ['prohibited AI uses', 'AI in government services', 'AI disclosure', 'deepfake prohibition', 'social credit scoring ban', 'self-harm AI ban'],
    sector_tags: ['government_services', 'healthcare', 'all_sectors'],
    technology_tags: ['decision_support_systems', 'deepfake', 'generative_ai', 'large_language_models'],
    key_obligations: ['Prohibit AI designed to induce self-harm or generate CSAM', 'Prohibit AI-generated deepfake pornography', 'Prohibit social credit scoring AI systems', 'State agencies and healthcare providers must disclose AI use in consumer interactions', 'AG enforcement with tiered civil penalties'],
  },
  'us-il-hb3773-2024': {
    legal_citation: '775 ILCS 5/2-102(A-5); HB 3773, P.A. 103-0668 (2024)',
    topics: ['AI in employment', 'algorithmic discrimination', 'hiring AI', 'employer AI obligations', 'disparate impact'],
    sector_tags: ['employment'],
    technology_tags: ['decision_support_systems', 'predictive_analytics', 'computer_vision', 'natural_language_processing'],
    key_obligations: ['Employers prohibited from using AI that produces discriminatory effect on protected classes in hiring', 'Strict liability for discriminatory AI employment outcomes', 'Notify employees and job applicants when AI is used in employment decisions', 'Comply with Illinois Human Rights Act remedies for violations'],
  },
  'us-wa-hb2225-2026': {
    legal_citation: 'HB 2225, 69th Wash. Leg., 2025–26 Sess.',
    topics: ['high-risk AI', 'algorithmic impact assessment', 'consumer rights in AI', 'human review rights', 'opt-out rights', 'AI discrimination'],
    sector_tags: ['employment', 'financial_services', 'healthcare', 'housing', 'government_services', 'consumer'],
    technology_tags: ['decision_support_systems', 'predictive_analytics', 'generative_ai', 'large_language_models'],
    key_obligations: ['Deployers of high-risk AI must conduct algorithmic impact assessments', 'Provide consumer disclosure of AI use in consequential decisions', 'Allow consumers to opt out of AI decisions and request human review', 'Private right of action under UDAP statutes', 'Safe harbor for documented compliance programs'],
  },
  'us-wa-hb1170-2026': {
    legal_citation: 'HB 1170, 69th Wash. Leg., 2025–26 Sess.',
    topics: ['AI content provenance', 'digital watermarking', 'AI-generated content disclosure', 'content authentication'],
    sector_tags: ['entertainment_media', 'telecommunications', 'consumer'],
    technology_tags: ['generative_ai', 'deepfake', 'image_synthesis', 'voice_cloning', 'content_moderation_ai'],
    key_obligations: ['AI developers with 1M+ monthly users must embed provenance data in AI-generated or materially altered images, video, audio', 'Provide free public detection tool for verifying AI-generated content'],
  },
  'us-nyc-ll144-2021': {
    legal_citation: 'N.Y.C. Admin. Code §§ 20-870 to 20-875; Local Law 144 of 2021',
    topics: ['AI in employment', 'automated employment decision tools', 'bias audits', 'hiring AI disclosure', 'algorithmic discrimination'],
    sector_tags: ['employment'],
    technology_tags: ['decision_support_systems', 'predictive_analytics', 'computer_vision', 'natural_language_processing'],
    key_obligations: ['Employers must conduct annual independent bias audit of automated employment decision tools', 'Publish bias audit results publicly on company website', 'Notify job candidates in advance that AEDT is being used in hiring process', 'Provide alternative selection procedure upon candidate request'],
  },
  'us-tn-elvisa-2024': {
    legal_citation: 'Tenn. Code Ann. §§ 47-25-1101 to 47-25-1108 (ELVIS Act); HB 2091, P.C. 1042 (2024)',
    topics: ['voice cloning', 'AI likeness protection', 'right of publicity', 'music industry AI', 'synthetic voice'],
    sector_tags: ['entertainment_media', 'consumer'],
    technology_tags: ['voice_cloning', 'generative_ai', 'deepfake'],
    key_obligations: ['Prohibition on using AI to mimic individual voice without consent', 'Civil cause of action for unauthorized AI voice cloning', 'Criminal misdemeanor for commercial unauthorized voice cloning', 'Applies to AI sound recordings distributed in commerce'],
  },
  'us-tn-sb1580-2026': {
    legal_citation: 'Tenn. Code Ann. § 63-1-160; SB 1580, P.A. 114-753 (2026)',
    topics: ['AI in mental health', 'chatbot therapy prohibition', 'healthcare AI disclosure', 'licensed professional AI'],
    sector_tags: ['healthcare'],
    technology_tags: ['natural_language_processing', 'large_language_models', 'agentic_systems'],
    key_obligations: ['AI chatbots may not claim to provide therapy or counseling services', 'May not represent as licensed mental health professional', 'Violations are unfair trade practices under Tennessee Consumer Protection Act', 'Private right of action: $5,000 per violation'],
  },
  'us-ut-sb149-2024': {
    legal_citation: 'Utah Code Ann. §§ 13-72-101 to 13-72-402 (Artificial Intelligence Policy Act); SB 149, 2024 Gen. Sess.',
    topics: ['AI disclosure on request', 'AI in regulated professions', 'state AI governance office', 'chatbot identity disclosure'],
    sector_tags: ['consumer', 'government_services', 'all_sectors'],
    technology_tags: ['natural_language_processing', 'generative_ai', 'large_language_models'],
    key_obligations: ['Regulated entities must disclose AI use to consumers upon request', 'Licensed professionals must provide advance notice of AI use', 'Establishes Utah Office of Artificial Intelligence Policy', 'Prohibits falsely representing AI as human'],
  },
  'us-in-hb1271-2026': {
    legal_citation: 'Ind. Code § 27-8-30; HB 1271, P.L. 2026 (2026)',
    topics: ['AI in health insurance', 'automated claims denial', 'healthcare AI human review', 'insurance adjudication AI'],
    sector_tags: ['healthcare', 'financial_services'],
    technology_tags: ['decision_support_systems', 'predictive_analytics'],
    key_obligations: ['Health insurers may not use fully automated AI to adjudicate claims without human review', 'Claims must be reviewed by qualified provider or licensed claims professional', 'Human override required before issuing AI-generated claim denials'],
  },
  'us-or-sb1546-2026': {
    legal_citation: 'ORS § 646A.810; SB 1546, 2026 Ore. Leg. Sess.',
    topics: ['chatbot disclosure', 'AI identity disclosure', 'conversational AI transparency', 'private right of action'],
    sector_tags: ['consumer', 'all_sectors'],
    technology_tags: ['natural_language_processing', 'large_language_models', 'agentic_systems'],
    key_obligations: ['Conversational AI operators must clearly disclose that users are interacting with AI', 'Disclosure required at start of interaction and upon sincere user request', 'Private right of action: $1,000 per violation, class actions permitted'],
  },
  'us-id-sb1297-2026': {
    legal_citation: 'Idaho Code §§ 48-1801 to 48-1808; SB 1297, 2026 Idaho Leg.',
    topics: ['chatbot disclosure', 'minor protection in AI', 'AI crisis protocols', 'sexual content AI ban', 'AI identity disclosure'],
    sector_tags: ['consumer', 'healthcare'],
    technology_tags: ['natural_language_processing', 'large_language_models'],
    key_obligations: ['Disclose AI identity to users, especially minors', 'Prohibit generating sexually explicit content or simulating romantic relationships with minors', 'Implement crisis referral protocols when suicidal ideation is detected', 'Penalty: $1,000 per violation, up to $500,000 per operator'],
  },
  'us-ne-lb525-2026': {
    legal_citation: 'Neb. Rev. Stat. §§ 87-901 to 87-910; LB 525, 109th Leg. (2026)',
    topics: ['chatbot disclosure', 'minor protection in AI', 'AI crisis protocols', 'AI identity disclosure'],
    sector_tags: ['consumer', 'healthcare'],
    technology_tags: ['natural_language_processing', 'large_language_models'],
    key_obligations: ['Disclose AI identity at start of user interaction', 'Prohibit CSAM generation', 'Mandate crisis referral protocols', 'Restrict romantic/sexual interactions with minors', 'Penalty: $1,000 per violation, up to $500,000 per operator'],
  },
  'us-me-ld2082-2026': {
    legal_citation: 'Me. Rev. Stat. tit. 32, § 18295; LD 2082, 132nd Me. Leg. (2026)',
    topics: ['AI therapy prohibition', 'AI in mental health', 'healthcare AI licensing', 'unlicensed AI practice prohibition'],
    sector_tags: ['healthcare'],
    technology_tags: ['natural_language_processing', 'large_language_models', 'agentic_systems'],
    key_obligations: ['Prohibit unlicensed entities from offering therapy using AI', 'Licensed practitioners may only use AI for administrative tasks with client consent', 'AI may not provide psychotherapy without licensed professional supervision', 'Penalty: $10,000 per violation'],
  },
  'us-md-hb895-2026': {
    legal_citation: 'Md. Code, Com. Law § 11-501 et seq. (as amended); HB 895, 2026 Md. Gen. Assem.',
    topics: ['algorithmic pricing', 'surveillance-based pricing', 'grocery pricing AI', 'consumer price discrimination'],
    sector_tags: ['consumer', 'financial_services'],
    technology_tags: ['predictive_analytics', 'decision_support_systems', 'recommendation_systems'],
    key_obligations: ['Food retailers ($100M+ revenue) prohibited from using personal consumer data to set individualized prices', 'Prohibit using purchase history or location data for price discrimination', 'AG enforcement; consumer civil penalties'],
  },
  'us-il-bipa-2008': {
    legal_citation: '740 ILCS 14/1 et seq. (Biometric Information Privacy Act); 2008 Ill. Laws 95-994',
    topics: ['biometric data collection', 'facial recognition', 'fingerprint collection', 'biometric consent', 'biometric data destruction', 'statutory damages'],
    sector_tags: ['employment', 'consumer', 'all_sectors'],
    technology_tags: ['biometric_data', 'facial_recognition', 'computer_vision'],
    key_obligations: ['Prior written consent required before collecting biometric identifiers', 'Publicly available written policy with retention schedule and destruction guidelines', 'No sale or profit from biometric data', 'Destroy data when purpose is fulfilled or 3 years, whichever first', 'Private right of action: $1,000–$5,000 per violation; class actions permitted'],
  },
  'eu-eu-aiact-2024': {
    legal_citation: 'Regulation (EU) 2024/1689 of the European Parliament and of the Council, O.J. L 2024/1689',
    topics: ['prohibited AI uses', 'high-risk AI classification', 'conformity assessment', 'transparency obligations', 'GPAI model regulation', 'AI systemic risk', 'biometric AI surveillance', 'AI safety testing', 'fundamental rights impact assessment'],
    sector_tags: ['all_sectors', 'government_services', 'healthcare', 'employment', 'financial_services', 'education', 'law_enforcement', 'critical_infrastructure'],
    technology_tags: ['generative_ai', 'large_language_models', 'facial_recognition', 'biometric_data', 'decision_support_systems', 'autonomous_systems', 'computer_vision', 'natural_language_processing'],
    key_obligations: ['Prohibited practices: real-time biometric surveillance in public, social scoring, manipulation of subliminal vulnerabilities', 'High-risk AI systems must undergo conformity assessment before market placement', 'General-purpose AI models (GPAI) with significant systemic risk require safety evaluations', 'Providers must maintain technical documentation and register in EU AI database', 'Deployers must conduct fundamental rights impact assessment for certain high-risk uses', 'EU AI Office to supervise GPAI models; national supervisory authorities for other systems'],
  },
  'eu-eu-gdpr-2016': {
    legal_citation: 'Regulation (EU) 2016/679 (GDPR), Art. 22, O.J. L 119/1 (May 4, 2016)',
    topics: ['automated decision-making', 'data subject rights', 'profiling', 'consent for automated processing', 'right to human review'],
    sector_tags: ['all_sectors'],
    technology_tags: ['decision_support_systems', 'predictive_analytics', 'recommendation_systems', 'generative_ai'],
    key_obligations: ['Right not to be subject to solely automated decisions with legal or significant effects', 'Data subject may request human review of automated decision', 'Controller must explain logic of automated decision upon request', 'Explicit consent required for profiling producing legal effects', 'Data protection impact assessment required for systematic automated processing'],
  },
  'cn-cn-genai-2023': {
    legal_citation: 'Interim Measures for the Management of Generative Artificial Intelligence Services, CAC/MIIT/MPS/MNR/PBC/SAMR No. 15 (2023)',
    topics: ['generative AI regulation', 'AI content labeling', 'security assessment', 'training data requirements', 'Chinese AI governance', 'content restrictions'],
    sector_tags: ['all_sectors', 'telecommunications', 'entertainment_media'],
    technology_tags: ['generative_ai', 'large_language_models', 'image_synthesis', 'deepfake'],
    key_obligations: ['AI-generated content must be labeled as AI-generated', 'Service providers must conduct security assessment before launch', 'Training data must not include prohibited content (defined broadly)', 'Providers responsible for content generated by their systems', 'Mechanisms to handle user complaints about generated content', 'Security filing with CAC for public-facing services'],
  },
  'cn-cn-deepsynthesis-2023': {
    legal_citation: 'Provisions on the Management of Deep Synthesis Internet Information Services, CAC/MPS Order No. 11 (2022, eff. Jan. 10, 2023)',
    topics: ['deepfake regulation', 'synthetic media', 'face-swapping', 'voice synthesis consent', 'AI-generated content labeling'],
    sector_tags: ['telecommunications', 'entertainment_media', 'consumer'],
    technology_tags: ['deepfake', 'image_synthesis', 'voice_cloning', 'computer_vision', 'generative_ai'],
    key_obligations: ['Providers must obtain consent before using individual likeness or voice for deep synthesis', 'Label AI-generated or significantly altered content with visible and non-visible markers', 'Security assessment and algorithm filing for public deep synthesis services', 'No creation of false news or content harmful to national security using deep synthesis'],
  },
  'cn-cn-ailabelling-2025': {
    legal_citation: 'GB 45438-2025 (AI-Generated Content Labelling Standard), SAMR/CAC (2025)',
    topics: ['AI content labeling standard', 'watermarking standard', 'content provenance', 'technical AI labeling requirements'],
    sector_tags: ['all_sectors', 'telecommunications', 'entertainment_media'],
    technology_tags: ['generative_ai', 'deepfake', 'image_synthesis', 'voice_cloning', 'content_moderation_ai'],
    key_obligations: ['Standardised technical requirements for labelling AI-generated content', 'Explicit and implicit labelling methods specified', 'Applies to text, images, audio, and video AI-generated content', 'Platforms must implement labeling infrastructure meeting GB 45438 specifications'],
  },
  'cn-cn-pipl-2021': {
    legal_citation: 'Personal Information Protection Law of the People\'s Republic of China, Order No. 91 of the President (2021)',
    topics: ['personal data protection', 'automated decision-making rights', 'profiling prohibition', 'data processing consent', 'individual AI rights'],
    sector_tags: ['all_sectors'],
    technology_tags: ['decision_support_systems', 'recommendation_systems', 'predictive_analytics'],
    key_obligations: ['Individuals have right to explanation of automated decision-making affecting them', 'Right to refuse to be subject to automated decisions in commercial marketing and credit', 'Explicit consent for processing sensitive personal information', 'Data localization requirements for critical personal information handlers'],
  },
  'cn-cn-trainingdata-2025': {
    legal_citation: 'GB/T 45694-2025 (Generative AI Training Data Standard), SAMR/MIIT (2025)',
    topics: ['AI training data quality', 'training data documentation', 'data annotation standards', 'training dataset governance'],
    sector_tags: ['all_sectors'],
    technology_tags: ['generative_ai', 'large_language_models'],
    key_obligations: ['Technical requirements for training data quality assessment', 'Documentation requirements for dataset composition and annotation', 'Data provenance and lineage tracking for training datasets', 'Prohibited content categories in training data'],
  },
  'cn-cn-algorec-2022': {
    legal_citation: 'Provisions on the Management of Algorithmic Recommendations, CAC/MIIT/MPS/SAMR/MCC Order No. 9 (2022)',
    topics: ['recommendation algorithm regulation', 'algorithmic transparency', 'filter bubbles', 'user opt-out of recommendations', 'discriminatory algorithms', 'labor platform algorithms'],
    sector_tags: ['telecommunications', 'entertainment_media', 'employment', 'consumer'],
    technology_tags: ['recommendation_systems', 'decision_support_systems', 'predictive_analytics'],
    key_obligations: ['Users have right to opt out of personalised algorithmic recommendations', 'Prohibition on using algorithms to create addictive features for minors', 'Prohibition on price discrimination using personal characteristics', 'Gig economy platforms must explain how work allocation algorithms function', 'Large platforms must file algorithm registry with CAC'],
  },
  'uk-uk-onlinesafety-2023': {
    legal_citation: 'Online Safety Act 2023, c. 50 (UK)',
    topics: ['AI-generated harmful content', 'platform safety duties', 'deepfake pornography', 'synthetic media harms', 'content moderation AI', 'child protection AI'],
    sector_tags: ['telecommunications', 'entertainment_media', 'consumer'],
    technology_tags: ['content_moderation_ai', 'deepfake', 'recommendation_systems', 'generative_ai', 'large_language_models'],
    key_obligations: ['Platforms must proactively assess and mitigate AI-generated harmful content risks', 'Criminal offence to share non-consensual intimate deepfake images', 'Category 1 services must conduct annual transparency reports on AI content moderation', 'Ofcom to produce codes of practice for AI content harms', 'Age verification requirements for platforms with AI-generated adult content'],
  },
  'kr-kr-aibasicact-2024': {
    legal_citation: 'Act on Development of Artificial Intelligence and Establishment of Trust (AI Basic Act), Act No. 20882 (2024)',
    topics: ['national AI strategy', 'high-impact AI', 'AI reliability', 'AI safety standards', 'AI accountability in Korea', 'foundation model regulation'],
    sector_tags: ['all_sectors', 'government_services'],
    technology_tags: ['generative_ai', 'large_language_models', 'decision_support_systems', 'autonomous_systems'],
    key_obligations: ['Government to establish national AI basic plan every 3 years', 'High-impact AI systems subject to conformity assessment', 'Providers of high-impact AI must disclose information to users', 'AI providers must implement measures to prevent discriminatory outcomes', 'National AI Commission to coordinate AI governance across ministries'],
  },
  'au-au-privacyact-2024': {
    legal_citation: 'Privacy and Other Legislation Amendment Act 2024 (Cth) (Automated Decision-Making Amendments)',
    topics: ['automated decision-making disclosure', 'privacy impact assessment', 'transparency in ADM', 'right to explanation in Australia'],
    sector_tags: ['government_services', 'financial_services', 'consumer', 'all_sectors'],
    technology_tags: ['decision_support_systems', 'predictive_analytics', 'recommendation_systems'],
    key_obligations: ['Organizations using ADM for decisions significantly affecting individuals must update privacy policies to disclose', 'Right to seek explanation of ADM decisions affecting individuals', 'Mandatory privacy impact assessments for high-privacy-risk activities including ADM', 'OAIC to develop guidance on ADM transparency requirements'],
  },
  'coe-coe-aiconv-2024': {
    legal_citation: 'Council of Europe Framework Convention on Artificial Intelligence and Human Rights, Democracy and the Rule of Law, CETS No. 225 (2024)',
    topics: ['AI human rights', 'AI democracy', 'rule of law AI', 'international AI treaty', 'government AI accountability', 'AI oversight mechanisms'],
    sector_tags: ['government_services', 'all_sectors'],
    technology_tags: ['all_sectors' as unknown as any, 'decision_support_systems', 'generative_ai', 'autonomous_systems'],
    key_obligations: ['Parties must ensure AI lifecycle activities respect human rights', 'Prohibition on AI that undermines integrity of democratic institutions', 'Right to seek review of AI-assisted decisions by public authorities', 'Parties must establish independent oversight bodies for AI', 'Transparency obligations for AI systems used by or on behalf of public authorities'],
  },
  'jp-jp-aiprom-2025': {
    legal_citation: 'Act for the Promotion of Research, Development and Utilization of Artificial Intelligence-related Technologies, Act No. 14 of 2025 (Japan)',
    topics: ['AI promotion', 'national AI strategy', 'AI safety standards', 'AI research framework', 'responsible AI development in Japan'],
    sector_tags: ['all_sectors', 'government_services'],
    technology_tags: ['generative_ai', 'large_language_models', 'autonomous_systems'],
    key_obligations: ['Government to develop basic AI policy and implementation guidelines', 'Establish AI Safety Institute with authority to conduct safety evaluations', 'Promote AI development while ensuring human-centric safety principles', 'Develop technical standards for AI safety assessment in consultation with international bodies'],
  },
  'us-ca-ccpa-cpra-2018': {
    legal_citation: 'Cal. Civ. Code §§ 1798.100–1798.199.100 (CCPA/CPRA); Prop. 24 (2020)',
    topics: ['automated decision-making rights', 'profiling opt-out', 'AI in consumer decisions', 'data rights re AI training', 'privacy rights'],
    sector_tags: ['financial_services', 'consumer', 'all_sectors'],
    technology_tags: ['decision_support_systems', 'recommendation_systems', 'predictive_analytics', 'generative_ai'],
    key_obligations: ['Right to opt out of automated decision-making using sensitive personal information', 'Right to know when profiling is used to make consequential decisions', 'Right to limit use of sensitive personal information in AI systems', 'CPPA to issue regulations on automated decision-making technology access and correction rights'],
  },
  'us-ny-raiseact-2025': {
    legal_citation: 'N.Y. Lab. Law §§ 193-aa to 193-ff (RAISE Act); S 3511-A / A 4736-A, 2025',
    topics: ['AI in employment', 'NY state AI act', 'high-risk AI employment', 'AI audit requirements', 'worker rights in AI'],
    sector_tags: ['employment', 'financial_services', 'housing', 'healthcare', 'education'],
    technology_tags: ['decision_support_systems', 'predictive_analytics', 'computer_vision', 'natural_language_processing'],
    key_obligations: ['Employers must notify workers before deploying high-risk AI in employment decisions', 'Conduct algorithmic impact assessments annually', 'Workers may request explanation of AI decision affecting them', 'Right to request human review of high-risk AI employment decision', 'Independent audit required for high-risk AI used in employment'],
  },
  'us-ky-sb4-2025': {
    legal_citation: 'KRS § 42.740 et seq. (AI Governance Framework); SB 4, 2025 Ky. Gen. Assem.',
    topics: ['AI governance framework', 'state AI policy', 'AI in government services', 'AI risk management'],
    sector_tags: ['government_services'],
    technology_tags: ['decision_support_systems', 'generative_ai', 'large_language_models'],
    key_obligations: ['Establishes AI governance framework for state government AI use', 'State agencies must inventory and assess AI systems for risk', 'Requires AI policies for high-risk government AI deployment', 'Creates AI advisory body within state government'],
  },
  'us-ct-pa25113-2025': {
    legal_citation: 'Conn. Gen. Stat. § 42-600a et seq.; PA 25-113, 2025 Conn. Gen. Assem.',
    topics: ['LLM training data disclosure', 'AI content labeling', 'generative AI transparency', 'Connecticut AI law'],
    sector_tags: ['all_sectors'],
    technology_tags: ['large_language_models', 'generative_ai'],
    key_obligations: ['LLM developers above compute threshold must publish training data summary', 'Disclosure must include categories of training data, sources, and whether copyrighted material was used', 'Content generated by covered LLMs must be labeled as AI-generated'],
  },
  'us-nh-hb143-2025': {
    legal_citation: 'RSA § 358-A:10-d; HB 143, 2025 N.H. Gen. Court',
    topics: ['AI child safety', 'chatbot child protection', 'AI CSAM prohibition', 'minor-facing AI disclosure'],
    sector_tags: ['consumer', 'healthcare'],
    technology_tags: ['natural_language_processing', 'large_language_models'],
    key_obligations: ['Chatbot operators must disclose AI identity to users under 18', 'Criminal prohibition on AI-generated CSAM', 'Crisis protocol required when minors express suicidal ideation to chatbot', 'AG enforcement'],
  },
  'us-me-hp1154-2025': {
    legal_citation: 'Me. Rev. Stat. tit. 10, § 1445 et seq.; HP 1154 / LD 1547, 132nd Me. Leg.',
    topics: ['chatbot transparency', 'AI identity disclosure', 'Maine AI law'],
    sector_tags: ['consumer', 'all_sectors'],
    technology_tags: ['natural_language_processing', 'large_language_models'],
    key_obligations: ['Chatbot operators must disclose AI identity when sincerely asked', 'Prohibition on claiming to be human when sincerely questioned', 'AG enforcement; civil penalties per violation'],
  },
  'us-ut-hb452-2024': {
    legal_citation: 'Utah Code Ann. § 13-72-501; HB 452, 2024 Utah Gen. Sess.',
    topics: ['mental health chatbot disclosure', 'AI in mental health', 'chatbot safety', 'therapy AI disclosure'],
    sector_tags: ['healthcare', 'consumer'],
    technology_tags: ['natural_language_processing', 'large_language_models'],
    key_obligations: ['Mental health chatbots must disclose AI identity clearly', 'Must provide access to licensed professional resources', 'Cannot represent as licensed mental health provider'],
  },
  'us-mt-sb212-2025': {
    legal_citation: 'Mont. Code Ann. § 2-17-601 et seq.; SB 212, 2025 Mont. Leg.',
    topics: ['AI compute rights', 'algorithmic discrimination ban', 'government AI restrictions', 'right to compute'],
    sector_tags: ['government_services', 'consumer'],
    technology_tags: ['decision_support_systems', 'generative_ai'],
    key_obligations: ['Government agencies prohibited from using AI to deny individual rights based on protected class', 'Residents have right to access and operate AI computing without government interference', 'Prohibition on social credit scoring by government entities'],
  },
  'us-mi-pa263266-2023': {
    legal_citation: 'MCL §§ 168.932c, 168.945a; PA 263-266, 2023 Mich. Acts (eff. Jan. 1, 2024)',
    topics: ['deepfakes in elections', 'political deepfakes prohibition', 'synthetic media elections', 'election integrity AI'],
    sector_tags: ['government_services', 'entertainment_media'],
    technology_tags: ['deepfake', 'image_synthesis', 'voice_cloning', 'generative_ai'],
    key_obligations: ['Prohibition on creating or distributing deepfake political ads without disclosure', 'Criminal prohibition on materially deceptive synthetic media about candidates', 'Disclosure required on AI-generated election communications', 'AG and election officials may seek injunctive relief'],
  },
  'us-wa-hb1205-2025': {
    legal_citation: 'RCW §§ 63.60.010 et seq. (as amended); HB 1205, 2025 Wash. Leg.',
    topics: ['digital likeness protection', 'voice cloning rights', 'AI likeness consent', 'right of publicity AI extension'],
    sector_tags: ['entertainment_media', 'consumer'],
    technology_tags: ['deepfake', 'voice_cloning', 'image_synthesis', 'generative_ai'],
    key_obligations: ['Extends Washington right of publicity to cover digital replicas and AI-generated likenesses', 'Consent required for commercial use of digital replica', 'Prohibition on non-consensual AI replicas for sexual content', 'Civil action: actual damages plus up to $10,000 per violation'],
  },
  'vn-vn-ailaw-2025': {
    legal_citation: 'Law No. 134/2025/QH15 on Artificial Intelligence (Vietnam)',
    topics: ['national AI strategy Vietnam', 'AI safety certification', 'high-risk AI Vietnam', 'AI standards', 'AI governance Asia'],
    sector_tags: ['all_sectors', 'government_services'],
    technology_tags: ['generative_ai', 'decision_support_systems', 'autonomous_systems'],
    key_obligations: ['AI developers and deployers of high-risk AI must register with competent authorities', 'High-risk AI must undergo conformity assessment', 'AI systems must meet safety and reliability standards set by Ministry of Science and Technology', 'Foreign AI service providers must comply with data localization requirements'],
  },
  'th-th-aiact-2026': {
    legal_citation: 'Artificial Intelligence Act B.E. 2569 (2026) (Thailand)',
    topics: ['AI safety Thailand', 'high-risk AI classification', 'AI certification', 'ASEAN AI regulation'],
    sector_tags: ['all_sectors', 'government_services'],
    technology_tags: ['generative_ai', 'decision_support_systems', 'autonomous_systems', 'large_language_models'],
    key_obligations: ['High-risk AI operators must obtain certification from National AI Committee', 'AI developers must register AI systems with regulatory authority', 'Disclosure obligations for AI use in public-facing applications', 'Establish AI Supervisory Committee with cross-ministry membership'],
  },
  'in-in-dpdpa-2023': {
    legal_citation: 'Digital Personal Data Protection Act, 2023, No. 22 of 2023 (India)',
    topics: ['personal data protection', 'automated processing rights', 'AI data governance', 'data fiduciary obligations', 'consent framework'],
    sector_tags: ['all_sectors', 'financial_services', 'healthcare', 'government_services'],
    technology_tags: ['decision_support_systems', 'predictive_analytics', 'generative_ai'],
    key_obligations: ['Data fiduciaries must process personal data only with consent for specified purposes', 'Right to access information about personal data processing', 'Right to erasure of personal data', 'Data fiduciaries must implement reasonable security safeguards', 'Significant data fiduciaries (volume threshold) subject to additional obligations including data protection officer'],
  },
  'sg-sg-onlinesafety-2025': {
    legal_citation: 'Online Safety (Relief) Act 2025 (Singapore)',
    topics: ['AI-generated harmful content', 'online safety platform duties', 'synthetic media harms', 'AI content moderation', 'digital harm prevention'],
    sector_tags: ['telecommunications', 'entertainment_media', 'consumer'],
    technology_tags: ['content_moderation_ai', 'deepfake', 'generative_ai', 'recommendation_systems'],
    key_obligations: ['Platforms must implement technical measures to prevent AI-generated CSAM', 'Designated online services must conduct risk assessments for AI-generated harms', 'Provide users with tools to reduce exposure to AI-generated harmful content', 'IMDA enforcement with significant civil penalties for non-compliance'],
  },
  'mx-mx-laborai-2026': {
    legal_citation: 'Decreto por el que se adiciona el Artículo 132 Bis de la Ley Federal del Trabajo (2026)',
    topics: ['AI voice/image rights', 'worker AI protections', 'employer AI restrictions', 'AI in employment Mexico', 'consent for AI likeness'],
    sector_tags: ['employment'],
    technology_tags: ['voice_cloning', 'deepfake', 'generative_ai'],
    key_obligations: ['Employers cannot use AI to replicate worker voice or image without explicit written consent', 'Workers have right to refuse AI likeness reproduction for commercial use', 'Labour law remedies apply for unauthorised AI use of worker identity'],
  },
}

// ─── New law entries ──────────────────────────────────────────────────────────

const NEW_LAWS = [
  {
    id: 'us-fed-nai-act-2020',
    jurisdiction: 'United States (Federal)',
    jurisdiction_type: 'federal',
    region: 'US',
    short_name: 'National AI Initiative Act (2020)',
    full_name: 'National Artificial Intelligence Initiative Act of 2020',
    instrument_type: 'statute',
    bill_number: 'Div. E, NDAA FY2021',
    enacted_date: '2021-01-01',
    effective_date: '2021-01-01',
    status: 'in_force',
    superseded_by: null,
    categories: ['scope_structure', 'enforcement_architecture'],
    primary_category: 'scope_structure',
    scope: 'comprehensive',
    who_regulated: ['government_only'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: false,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: false, data_rights_re_training: false,
      private_right_of_action: false, safe_harbor: false, prohibited_categories: false,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['NIST', 'NSF', 'OSTP', 'NITRD Program'],
    max_penalty: null,
    max_penalty_usd_approx: null,
    preemption_status: 'n/a',
    preemption_notes: null,
    legal_family: 'standalone',
    inspired_by: [],
    influenced: ['us-fed-eo14110-2023'],
    official_text_url: 'https://www.congress.gov/bill/116th-congress/house-bill/6216',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'The foundational US federal AI law, enacted as Division E of the FY2021 NDAA. Establishes the National AI Initiative to coordinate federal AI R&D, creates the National AI Initiative Office within OSTP, requires a National AI Research Resource, and mandates an AI technical standards program at NIST. Sets the institutional framework for subsequent federal AI governance.',
    notable: 'Provided the institutional scaffolding for subsequent Biden EO 14110 and the AI Safety Institute. First binding federal AI coordination statute.',
    legal_citation: 'Pub. L. 116-283, Div. E, §§ 5001–5901 (National AI Initiative Act)',
    topics: ['national AI coordination', 'federal AI research policy', 'AI standards development', 'AI workforce development', 'government AI strategy'],
    sector_tags: ['government_services', 'all_sectors'],
    technology_tags: ['generative_ai', 'autonomous_systems', 'decision_support_systems'],
    key_obligations: ['Establishes National AI Initiative Office in OSTP to coordinate federal AI activities', 'NIST to develop voluntary AI standards and frameworks', 'NSF and DOE to expand AI research investments', 'National AI Research Resource to democratize access to AI compute and data', 'Annual report to Congress on federal AI R&D spending'],
  },
  {
    id: 'us-fed-defiance-act-2024',
    jurisdiction: 'United States (Federal)',
    jurisdiction_type: 'federal',
    region: 'US',
    short_name: 'DEFIANCE Act (2024)',
    full_name: 'Disrupt Explicit Forged Images and Non-Consensual Edits Act of 2024',
    instrument_type: 'statute',
    bill_number: 'S. 4569',
    enacted_date: '2024-07-30',
    effective_date: '2024-07-30',
    status: 'in_force',
    superseded_by: null,
    categories: ['content_synthetic_media', 'individual_rights'],
    primary_category: 'content_synthetic_media',
    scope: 'single_issue',
    who_regulated: ['both'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: false,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: true, data_rights_re_training: false,
      private_right_of_action: true, safe_harbor: false, prohibited_categories: true,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['US District Courts (civil)', 'DOJ (criminal)'],
    max_penalty: 'Up to 10 years imprisonment (criminal); actual damages + attorney fees (civil)',
    max_penalty_usd_approx: null,
    preemption_status: 'n/a',
    preemption_notes: 'Federal civil remedy; does not preempt state NCII laws',
    legal_family: 'standalone',
    inspired_by: [],
    influenced: ['us-fed-take-it-down-2026'],
    official_text_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/4569',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Creates a federal civil cause of action for victims of non-consensual intimate digital forgeries (AI-generated NCII). Plaintiffs may sue any person who knowingly produces or possesses NCII with intent to distribute when they know or recklessly disregard that the depicted person did not consent. Allows injunctive relief, actual damages, and attorney fees. Also creates criminal liability under 18 U.S.C.',
    notable: 'Predates TAKE IT DOWN Act; provides civil remedy whereas TAKE IT DOWN addresses platform takedown obligations. Together they form the US federal framework for AI-generated NCII.',
    legal_citation: 'S. 4569, 118th Cong. (2024); amends 18 U.S.C. § 2252E et seq.',
    topics: ['non-consensual intimate imagery', 'AI-generated pornography', 'civil remedy for deepfake NCII', 'revenge porn AI'],
    sector_tags: ['consumer', 'entertainment_media'],
    technology_tags: ['deepfake', 'image_synthesis', 'generative_ai'],
    key_obligations: ['Civil cause of action for victims of NCII deepfakes', 'Defendant liable if they knowingly produce or possess NCII with intent to distribute', 'Injunctive relief and actual damages available', 'Criminal penalties under amended federal statute'],
  },
  {
    id: 'us-ca-ab1836-2024',
    jurisdiction: 'California',
    jurisdiction_type: 'state',
    region: 'US-CA',
    short_name: 'California AB 1836 (Deceased Performer AI)',
    full_name: 'Use of Digital Replicas of Deceased Performers Act',
    instrument_type: 'statute',
    bill_number: 'AB 1836',
    enacted_date: '2024-09-17',
    effective_date: '2025-01-01',
    status: 'in_force',
    superseded_by: null,
    categories: ['content_synthetic_media', 'individual_rights'],
    primary_category: 'content_synthetic_media',
    scope: 'sector_specific',
    who_regulated: ['both'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: false,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: true, data_rights_re_training: false,
      private_right_of_action: true, safe_harbor: false, prohibited_categories: false,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['California courts (civil)'],
    max_penalty: 'Actual damages or $75,000 per violation; punitive damages available',
    max_penalty_usd_approx: 75000,
    preemption_status: 'low_risk',
    preemption_notes: null,
    legal_family: 'standalone',
    inspired_by: ['us-tn-elvisa-2024'],
    influenced: [],
    official_text_url: 'https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240AB1836',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Extends California right of publicity protections to deceased performers by requiring prior consent from the estate before creating or using an AI-generated digital replica of a deceased performer in an audiovisual work, sound recording, or live performance. Applies to performances and recordings made during the performer\'s life.',
    notable: 'Part of a broader 2024 California AI legislative package targeting entertainment industry AI use. Signed by Governor Newsom.',
    legal_citation: 'Cal. Lab. Code §§ 3344.1 (as amended); AB 1836, 2023–24 Leg. Sess.',
    topics: ['deceased performer rights', 'digital replica consent', 'right of publicity AI', 'posthumous AI likeness', 'entertainment industry AI'],
    sector_tags: ['entertainment_media'],
    technology_tags: ['deepfake', 'image_synthesis', 'voice_cloning', 'generative_ai'],
    key_obligations: ['Prior consent from estate required to create AI digital replica of deceased performer', 'Applies to audiovisual works, sound recordings, and live performances', 'Civil cause of action with actual damages or $75,000 per violation', 'Estate holds rights for 70 years post-death'],
  },
  {
    id: 'us-ca-ab2602-2024',
    jurisdiction: 'California',
    jurisdiction_type: 'state',
    region: 'US-CA',
    short_name: 'California AB 2602 (AI in Entertainment Contracts)',
    full_name: 'Contracts Involving AI Replicas of Performers Act',
    instrument_type: 'statute',
    bill_number: 'AB 2602',
    enacted_date: '2024-09-17',
    effective_date: '2025-01-01',
    status: 'in_force',
    superseded_by: null,
    categories: ['content_synthetic_media', 'sector_specific_employment'],
    primary_category: 'sector_specific_employment',
    scope: 'sector_specific',
    who_regulated: ['both'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: false,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: true,
      biometric_protection: false, voice_likeness_protection: true, data_rights_re_training: false,
      private_right_of_action: true, safe_harbor: false, prohibited_categories: false,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['California courts (civil)', 'California Labor Commissioner'],
    max_penalty: 'Contract unenforceable; civil damages',
    max_penalty_usd_approx: null,
    preemption_status: 'low_risk',
    preemption_notes: null,
    legal_family: 'standalone',
    inspired_by: [],
    influenced: [],
    official_text_url: 'https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240AB2602',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Voids provisions in entertainment contracts that grant employers the right to use an AI replica of a performer to replace work the performer would otherwise perform, unless the performer receives specific, individualized notice and representation by a qualified representative. Applies to contracts for audiovisual and sound recording work.',
    notable: 'Labor protections for performers against AI replacement in contracts. Companion bill to AB 1836 on the employment side.',
    legal_citation: 'Cal. Lab. Code § 3344.1(c) (as amended); AB 2602, 2023–24 Leg. Sess.',
    topics: ['performer contract rights', 'AI replacement protection', 'entertainment contracts AI', 'digital replica in employment', 'labor protection from AI'],
    sector_tags: ['entertainment_media', 'employment'],
    technology_tags: ['deepfake', 'voice_cloning', 'image_synthesis', 'generative_ai'],
    key_obligations: ['AI replica contract provisions unenforceable unless performer receives individual notice', 'Performer must be represented by qualified representative before signing AI replica rights away', 'Applies to contracts for audiovisual and recorded performance work'],
  },
  {
    id: 'us-mn-hf4114-2024',
    jurisdiction: 'Minnesota',
    jurisdiction_type: 'state',
    region: 'US-MN',
    short_name: 'Minnesota HF 4114 (AI Elections Disclosure)',
    full_name: 'Minnesota Artificial Intelligence and Elections Disclosure Act',
    instrument_type: 'statute',
    bill_number: 'HF 4114',
    enacted_date: '2024-05-20',
    effective_date: '2024-08-01',
    status: 'in_force',
    superseded_by: null,
    categories: ['content_synthetic_media', 'transparency_disclosure'],
    primary_category: 'content_synthetic_media',
    scope: 'single_issue',
    who_regulated: ['both', 'platforms'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: true,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: false, data_rights_re_training: false,
      private_right_of_action: true, safe_harbor: false, prohibited_categories: true,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['Minnesota Secretary of State', 'Minnesota courts (civil)'],
    max_penalty: 'Civil action; up to $1,000 per violation or actual damages',
    max_penalty_usd_approx: 1000,
    preemption_status: 'low_risk',
    preemption_notes: null,
    legal_family: 'standalone',
    inspired_by: ['us-mi-pa263266-2023'],
    influenced: [],
    official_text_url: 'https://www.revisor.mn.gov/bills/bill.php?b=House&f=HF4114&ssn=0&y=2024',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Prohibits the creation or distribution of materially deceptive AI-generated audio or visual media depicting a political candidate within 90 days of an election without a disclosure label. Requires prominent disclosure that content is AI-generated. Provides private right of action for candidates.',
    notable: 'One of a wave of 2024 state laws targeting AI-generated deepfake election content. Minnesota was an early mover.',
    legal_citation: 'Minn. Stat. § 211B.17 (as amended); HF 4114, 2024 Minn. Leg.',
    topics: ['deepfakes in elections', 'political deepfake disclosure', 'AI in elections', 'synthetic media elections', 'election integrity'],
    sector_tags: ['government_services', 'entertainment_media'],
    technology_tags: ['deepfake', 'image_synthesis', 'voice_cloning', 'generative_ai'],
    key_obligations: ['Disclosure label required on AI-generated political media within 90 days of election', 'Prohibition on materially deceptive AI-generated candidate depictions without disclosure', 'Private right of action for affected candidates', 'Platform liability for knowing distribution of non-disclosed AI election content'],
  },
  {
    id: 'us-fl-sb262-2024',
    jurisdiction: 'Florida',
    jurisdiction_type: 'state',
    region: 'US-FL',
    short_name: 'Florida SB 262 (AI in Elections)',
    full_name: 'Florida Deceptive AI Content in Political Advertising Act',
    instrument_type: 'statute',
    bill_number: 'SB 262',
    enacted_date: '2024-06-01',
    effective_date: '2024-07-01',
    status: 'in_force',
    superseded_by: null,
    categories: ['content_synthetic_media', 'transparency_disclosure'],
    primary_category: 'content_synthetic_media',
    scope: 'single_issue',
    who_regulated: ['both', 'platforms'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: true,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: false, data_rights_re_training: false,
      private_right_of_action: false, safe_harbor: false, prohibited_categories: false,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['Florida Division of Elections', 'Florida Attorney General'],
    max_penalty: '$1,000 per day for political committee non-disclosure violations',
    max_penalty_usd_approx: 1000,
    preemption_status: 'low_risk',
    preemption_notes: null,
    legal_family: 'standalone',
    inspired_by: ['us-mi-pa263266-2023'],
    influenced: [],
    official_text_url: 'https://www.flsenate.gov/Session/Bill/2024/262/BillText/er/PDF',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Requires political advertisements containing AI-generated content to include a clear and conspicuous disclosure stating the content was "created in whole or in part with the use of generative artificial intelligence." Applies to television, radio, digital, and print political advertising in Florida.',
    notable: 'Governor DeSantis signed this while vetoing a broader AI bill. Florida takes a narrow, disclosure-only approach to AI in elections.',
    legal_citation: 'Fla. Stat. § 106.011(29); § 106.143(1)(c); SB 262, 2024 Fla. Leg.',
    topics: ['AI political advertising disclosure', 'deepfakes in elections', 'political ad AI labeling', 'election content AI'],
    sector_tags: ['government_services'],
    technology_tags: ['generative_ai', 'deepfake', 'image_synthesis', 'voice_cloning'],
    key_obligations: ['Political ads containing AI-generated content must include prominent disclosure label', 'Disclosure must state content was created using generative AI', 'Applies to all political advertising formats: TV, radio, digital, print', 'Division of Elections enforcement'],
  },
  {
    id: 'us-ga-sb396-2024',
    jurisdiction: 'Georgia',
    jurisdiction_type: 'state',
    region: 'US-GA',
    short_name: 'Georgia SB 396 (AI Likeness Protection)',
    full_name: 'Georgia Artificial Intelligence in Creative Content Act',
    instrument_type: 'statute',
    bill_number: 'SB 396',
    enacted_date: '2024-04-18',
    effective_date: '2024-07-01',
    status: 'in_force',
    superseded_by: null,
    categories: ['content_synthetic_media', 'biometric_identity'],
    primary_category: 'content_synthetic_media',
    scope: 'sector_specific',
    who_regulated: ['both'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: false,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: true, data_rights_re_training: false,
      private_right_of_action: true, safe_harbor: false, prohibited_categories: false,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['Georgia courts (civil)'],
    max_penalty: 'Actual damages; injunctive relief',
    max_penalty_usd_approx: null,
    preemption_status: 'low_risk',
    preemption_notes: null,
    legal_family: 'standalone',
    inspired_by: ['us-tn-elvisa-2024'],
    influenced: [],
    official_text_url: 'https://www.legis.ga.gov/legislation/65358',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Extends Georgia\'s right of publicity statute to prohibit the creation of AI-generated synthetic depictions of individuals\' likeness or voice without consent for commercial purposes. Provides civil remedies including actual damages and injunctive relief. Focuses on performers and artists in the entertainment industry.',
    notable: 'Part of the entertainment industry-driven wave of 2024 AI likeness protection laws. Georgia is home to a major film and music industry.',
    legal_citation: 'Ga. Code Ann. §§ 51-5-1 to 51-5-10 (as amended); SB 396, 2024 Ga. Gen. Assem.',
    topics: ['AI likeness rights', 'right of publicity AI', 'voice cloning consent', 'entertainment AI protection', 'synthetic performer depiction'],
    sector_tags: ['entertainment_media', 'consumer'],
    technology_tags: ['deepfake', 'voice_cloning', 'image_synthesis', 'generative_ai'],
    key_obligations: ['Consent required before creating AI depiction of individual likeness or voice for commercial use', 'Civil cause of action: actual damages and injunctive relief', 'Applies to synthetic audio and visual depictions in commercial contexts'],
  },
  {
    id: 'us-in-sb10-2024',
    jurisdiction: 'Indiana',
    jurisdiction_type: 'state',
    region: 'US-IN',
    short_name: 'Indiana SB 10 (Deepfakes Elections)',
    full_name: 'Indiana Deceptive AI Political Content Prohibition Act',
    instrument_type: 'statute',
    bill_number: 'SB 10',
    enacted_date: '2024-03-11',
    effective_date: '2024-07-01',
    status: 'in_force',
    superseded_by: null,
    categories: ['content_synthetic_media'],
    primary_category: 'content_synthetic_media',
    scope: 'single_issue',
    who_regulated: ['both'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: true,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: false, data_rights_re_training: false,
      private_right_of_action: false, safe_harbor: false, prohibited_categories: true,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['Indiana Election Commission', 'Indiana Attorney General'],
    max_penalty: '$1,000 per violation',
    max_penalty_usd_approx: 1000,
    preemption_status: 'low_risk',
    preemption_notes: null,
    legal_family: 'standalone',
    inspired_by: ['us-mi-pa263266-2023'],
    influenced: [],
    official_text_url: 'https://iga.in.gov/legislative/2024/bills/senate/10/',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Prohibits the distribution of materially deceptive AI-generated audio or visual media depicting a candidate within 90 days before an election without clear disclosure. Requires a disclosure label stating the content is AI-generated. Indiana Election Commission may impose civil penalties.',
    notable: null,
    legal_citation: 'Ind. Code § 3-14-3-3.5; SB 10, 2024 Ind. Gen. Assem.',
    topics: ['deepfakes in elections', 'political deepfake prohibition', 'AI election content disclosure', 'synthetic political media'],
    sector_tags: ['government_services'],
    technology_tags: ['deepfake', 'image_synthesis', 'voice_cloning', 'generative_ai'],
    key_obligations: ['Prohibition on distributing materially deceptive AI political content within 90 days of election', 'Disclosure label required on AI-generated political content', 'Indiana Election Commission civil penalty enforcement'],
  },
  {
    id: 'us-il-aiea-2024',
    jurisdiction: 'Illinois',
    jurisdiction_type: 'state',
    region: 'US-IL',
    short_name: 'Illinois AIEA (AI Employment Analytics)',
    full_name: 'Illinois Artificial Intelligence Video Interview Act — Extended to Employment Analytics',
    instrument_type: 'statute',
    bill_number: 'HB 4367',
    enacted_date: '2024-08-09',
    effective_date: '2025-01-01',
    status: 'in_force',
    superseded_by: null,
    categories: ['sector_specific_employment', 'algorithmic_accountability'],
    primary_category: 'sector_specific_employment',
    scope: 'sector_specific',
    who_regulated: ['deployers'],
    provisions: {
      ai_interaction_disclosure: true, training_data_disclosure: false, content_labelling: false,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: true,
      anti_discrimination_standard: 'impact_based', human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: false, data_rights_re_training: false,
      private_right_of_action: false, safe_harbor: false, prohibited_categories: false,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['Illinois Department of Labor'],
    max_penalty: 'Civil rights damages under Illinois Human Rights Act',
    max_penalty_usd_approx: null,
    preemption_status: 'low_risk',
    preemption_notes: null,
    legal_family: 'us_consumer_protection',
    inspired_by: ['us-nyc-ll144-2021'],
    influenced: [],
    official_text_url: 'https://www.ilga.gov/legislation/publicacts/103/PDF/103-0754.pdf',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Extends Illinois AI employment obligations to include AI-assisted resume screening and candidate evaluation tools, beyond the earlier video interview AI law. Employers must notify candidates when AI analytics are used in the screening process and share race/ethnicity data of candidates reviewed by AI with the state annually.',
    notable: 'Builds on Illinois\' 2020 AI Video Interview Act, which was the first US state law regulating AI in hiring.',
    legal_citation: 'Ill. Comp. Stat. 775 ILCS 5/2-102; HB 4367, P.A. 103-0754 (2024)',
    topics: ['AI in hiring', 'resume screening AI', 'employment analytics disclosure', 'AI recruitment audit', 'disparate impact employment AI'],
    sector_tags: ['employment'],
    technology_tags: ['decision_support_systems', 'computer_vision', 'natural_language_processing', 'predictive_analytics'],
    key_obligations: ['Notify candidates when AI analytics tools are used in screening', 'Annual report to state on race/ethnicity demographics of candidates reviewed by AI', 'Comply with Illinois Human Rights Act anti-discrimination requirements'],
  },
  {
    id: 'us-nc-sb815-2024',
    jurisdiction: 'North Carolina',
    jurisdiction_type: 'state',
    region: 'US-NC',
    short_name: 'North Carolina SB 815 (AI in Elections)',
    full_name: 'North Carolina Protecting Elections from Deceptive AI Act',
    instrument_type: 'statute',
    bill_number: 'SB 815',
    enacted_date: '2024-10-03',
    effective_date: '2024-10-03',
    status: 'in_force',
    superseded_by: null,
    categories: ['content_synthetic_media'],
    primary_category: 'content_synthetic_media',
    scope: 'single_issue',
    who_regulated: ['both'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: true,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: false, data_rights_re_training: false,
      private_right_of_action: false, safe_harbor: false, prohibited_categories: true,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['North Carolina State Board of Elections'],
    max_penalty: 'Class 2 misdemeanor; campaign finance violation penalties',
    max_penalty_usd_approx: null,
    preemption_status: 'low_risk',
    preemption_notes: null,
    legal_family: 'standalone',
    inspired_by: ['us-mi-pa263266-2023'],
    influenced: [],
    official_text_url: 'https://www.ncleg.gov/Sessions/2023/Bills/Senate/PDF/S815v6.pdf',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Prohibits creating or distributing materially deceptive AI-generated media depicting a candidate within 60 days before an election without a clear disclosure label. Criminal misdemeanor for knowing violations. The disclosure must be conspicuous and state that the content contains AI-generated material.',
    notable: null,
    legal_citation: 'N.C. Gen. Stat. § 163-278.40 et seq.; SB 815, 2023–24 N.C. Gen. Assem.',
    topics: ['deepfakes in elections', 'AI election content disclosure', 'candidate deepfake prohibition', 'political AI content'],
    sector_tags: ['government_services'],
    technology_tags: ['deepfake', 'image_synthesis', 'voice_cloning', 'generative_ai'],
    key_obligations: ['Prohibition on deceptive AI political media within 60 days of election without disclosure', 'Disclosure must state content is AI-generated', 'Class 2 misdemeanor for knowing violations'],
  },
  {
    id: 'us-nv-ab384-2024',
    jurisdiction: 'Nevada',
    jurisdiction_type: 'state',
    region: 'US-NV',
    short_name: 'Nevada AB 384 (AI in Elections)',
    full_name: 'Nevada Deceptive Artificial Intelligence in Elections Act',
    instrument_type: 'statute',
    bill_number: 'AB 384',
    enacted_date: '2024-06-03',
    effective_date: '2024-10-01',
    status: 'in_force',
    superseded_by: null,
    categories: ['content_synthetic_media'],
    primary_category: 'content_synthetic_media',
    scope: 'single_issue',
    who_regulated: ['both'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: true,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: false, data_rights_re_training: false,
      private_right_of_action: false, safe_harbor: false, prohibited_categories: true,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['Nevada Secretary of State', 'Nevada Attorney General'],
    max_penalty: 'Category E felony (criminal) for deceptive election deepfakes',
    max_penalty_usd_approx: null,
    preemption_status: 'low_risk',
    preemption_notes: null,
    legal_family: 'standalone',
    inspired_by: ['us-mi-pa263266-2023'],
    influenced: [],
    official_text_url: 'https://www.leg.state.nv.us/App/NELIS/REL/82nd2023/Bill/9999/Text',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Prohibits the knowing distribution of materially deceptive AI-generated media depicting a candidate within 60 days of an election without disclosure. Makes knowing violations a Category E felony. Requires disclosure label on AI-generated election content. Nevada\'s enhanced criminal penalties distinguish it from most state election deepfake laws.',
    notable: 'Category E felony for knowing violation makes Nevada one of the strictest states on AI election deepfakes.',
    legal_citation: 'NRS § 294A.400 et seq.; AB 384, 82nd Nev. Leg. (2024)',
    topics: ['deepfakes in elections', 'AI election fraud', 'synthetic political media', 'election integrity AI'],
    sector_tags: ['government_services'],
    technology_tags: ['deepfake', 'image_synthesis', 'voice_cloning', 'generative_ai'],
    key_obligations: ['Prohibition on distributing deceptive AI election media within 60 days of election', 'Disclosure label required on AI-generated political content', 'Category E felony for knowing violations'],
  },
  {
    id: 'eu-eu-pld-2024',
    jurisdiction: 'European Union',
    jurisdiction_type: 'international',
    region: 'EU',
    short_name: 'EU Product Liability Directive (2024)',
    full_name: 'Directive (EU) 2024/2853 on Liability for Defective Products',
    instrument_type: 'regulation',
    bill_number: null,
    enacted_date: '2024-11-18',
    effective_date: '2026-12-09',
    status: 'enacted_not_yet_effective',
    superseded_by: null,
    categories: ['enforcement_architecture', 'individual_rights'],
    primary_category: 'enforcement_architecture',
    scope: 'comprehensive',
    who_regulated: ['developers', 'deployers'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: false,
      risk_classification_system: false, impact_assessment_required: false, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: false, data_rights_re_training: false,
      private_right_of_action: true, safe_harbor: false, prohibited_categories: false,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['Member State courts (civil)'],
    max_penalty: 'Full compensation for damages (no cap)',
    max_penalty_usd_approx: null,
    preemption_status: 'preempts_lower',
    preemption_notes: 'Replaces 1985 Product Liability Directive (85/374/EEC); harmonizes EU member state product liability',
    legal_family: 'eu_risk_based',
    inspired_by: ['eu-eu-aiact-2024'],
    influenced: [],
    official_text_url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024L2853',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Modernises EU product liability rules to cover AI systems and software. Clarifies that AI systems are "products" under EU law; manufacturers and importers are strictly liable for damage caused by defective AI products. Introduces disclosure obligations for defendants to share technical documentation, alleviating the burden of proof problem for victims of AI harms.',
    notable: 'Companion to EU AI Act — the AI Act sets ex ante regulatory requirements; the revised PLD creates the ex post civil liability pathway for AI harm. Together they form the EU AI liability framework.',
    legal_citation: 'Directive (EU) 2024/2853, O.J. L 2024/2853 (Nov. 18, 2024)',
    topics: ['AI product liability', 'civil liability for AI', 'AI defect liability', 'AI harm compensation', 'AI as product', 'burden of proof AI'],
    sector_tags: ['all_sectors', 'consumer'],
    technology_tags: ['generative_ai', 'autonomous_systems', 'decision_support_systems', 'large_language_models'],
    key_obligations: ['AI systems are "products" — manufacturers strictly liable for defective AI causing damage', 'Defendants must disclose technical documentation when requested by plaintiff courts', 'Presumption of causation where defect is plausible and damage consistent with type', 'Member states must implement by December 9, 2026'],
  },
  {
    id: 'eu-eu-cra-2024',
    jurisdiction: 'European Union',
    jurisdiction_type: 'international',
    region: 'EU',
    short_name: 'EU Cyber Resilience Act (2024)',
    full_name: 'Regulation (EU) 2024/2847 on Cybersecurity Requirements for Products with Digital Elements',
    instrument_type: 'regulation',
    bill_number: null,
    enacted_date: '2024-10-10',
    effective_date: '2027-12-11',
    status: 'enacted_not_yet_effective',
    superseded_by: null,
    categories: ['algorithmic_accountability', 'enforcement_architecture'],
    primary_category: 'algorithmic_accountability',
    scope: 'comprehensive',
    who_regulated: ['developers'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: false,
      risk_classification_system: true, impact_assessment_required: true, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: false,
      biometric_protection: false, voice_likeness_protection: false, data_rights_re_training: false,
      private_right_of_action: false, safe_harbor: false, prohibited_categories: false,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['National market surveillance authorities', 'ENISA'],
    max_penalty: '€15,000,000 or 2.5% of global annual turnover (whichever higher)',
    max_penalty_usd_approx: 15000000,
    preemption_status: 'preempts_lower',
    preemption_notes: 'Harmonises EU cybersecurity requirements for digital products',
    legal_family: 'eu_risk_based',
    inspired_by: ['eu-eu-aiact-2024'],
    influenced: [],
    official_text_url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R2847',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Establishes mandatory cybersecurity requirements for all products with digital elements placed on the EU market, including AI systems. Manufacturers must conduct security risk assessments, implement security-by-design, provide security updates throughout product lifecycle, and report actively exploited vulnerabilities within 24 hours. AI systems that are "products with digital elements" must comply alongside AI Act requirements.',
    notable: 'The CRA applies to AI systems as products with digital elements, creating overlapping obligations with the EU AI Act. Critical AI products require third-party security assessment.',
    legal_citation: 'Regulation (EU) 2024/2847, O.J. L 2024/2847 (Oct. 10, 2024)',
    topics: ['AI cybersecurity requirements', 'software security by design', 'vulnerability disclosure', 'AI product security', 'digital product regulation'],
    sector_tags: ['all_sectors', 'critical_infrastructure', 'consumer'],
    technology_tags: ['generative_ai', 'autonomous_systems', 'decision_support_systems', 'agentic_systems'],
    key_obligations: ['Security risk assessment required before market placement', 'Implement security-by-design and security-by-default', 'Provide security updates throughout product lifecycle (minimum 5 years)', 'Report exploited vulnerabilities to ENISA within 24 hours', 'Critical products require third-party conformity assessment'],
  },
  {
    id: 'br-br-aiact-2025',
    jurisdiction: 'Brazil',
    jurisdiction_type: 'international',
    region: 'LATAM',
    short_name: 'Brazil AI Act (Lei n° 2338/2025)',
    full_name: 'Marco Legal da Inteligência Artificial (Brazilian AI Framework Law)',
    instrument_type: 'statute',
    bill_number: 'PL 2338/2023',
    enacted_date: '2025-04-25',
    effective_date: '2026-01-01',
    status: 'in_force',
    superseded_by: null,
    categories: ['algorithmic_accountability', 'individual_rights', 'enforcement_architecture'],
    primary_category: 'algorithmic_accountability',
    scope: 'comprehensive',
    who_regulated: ['developers', 'deployers', 'both'],
    provisions: {
      ai_interaction_disclosure: true, training_data_disclosure: true, content_labelling: true,
      risk_classification_system: true, impact_assessment_required: true, anti_discrimination: true,
      anti_discrimination_standard: 'impact_based', human_review_right: true, opt_out_right: true,
      biometric_protection: true, voice_likeness_protection: false, data_rights_re_training: false,
      private_right_of_action: true, safe_harbor: true, prohibited_categories: true,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['ANPD (National Data Protection Authority)', 'SENACON (Consumer Protection Secretariat)', 'Brazilian courts'],
    max_penalty: 'R$50,000,000 per violation (~$9M USD) or 2% of revenue',
    max_penalty_usd_approx: 9000000,
    preemption_status: 'n/a',
    preemption_notes: null,
    legal_family: 'eu_risk_based',
    inspired_by: ['eu-eu-aiact-2024', 'eu-eu-gdpr-2016'],
    influenced: [],
    official_text_url: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2417005',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Brazil\'s comprehensive AI framework law, passed after three years of parliamentary debate. Establishes a risk-based regulatory regime modeled partly on the EU AI Act. Creates prohibited AI categories, mandates impact assessments for high-risk AI, requires AI interaction disclosure, and grants individuals rights to contest AI decisions. ANPD is the primary enforcement authority alongside sector regulators.',
    notable: 'First comprehensive AI framework law in Latin America. Effective January 1, 2026. ANPD must issue implementing regulations within 180 days of enactment.',
    legal_citation: 'Lei n° 2338/2023 (enacted 2025) — Marco Legal da IA (Brazil)',
    topics: ['Brazilian AI regulation', 'Latin America AI law', 'risk-based AI framework', 'AI impact assessment', 'prohibited AI', 'AI rights Brazil'],
    sector_tags: ['all_sectors', 'government_services', 'healthcare', 'employment', 'financial_services'],
    technology_tags: ['generative_ai', 'decision_support_systems', 'biometric_data', 'predictive_analytics', 'large_language_models'],
    key_obligations: ['Disclosure required when interacting with AI system', 'High-risk AI systems require prior algorithmic impact assessment', 'Prohibited AI categories include social scoring and manipulative AI', 'Human review right for AI decisions with significant effects', 'Private right of action for individuals harmed by prohibited AI', 'AI providers must register high-risk systems with ANPD'],
  },
  {
    id: 'in-in-dpdpa-rules-2025',
    jurisdiction: 'India',
    jurisdiction_type: 'international',
    region: 'APAC',
    short_name: 'India DPDPA Rules 2025',
    full_name: 'Digital Personal Data Protection Rules, 2025 (India)',
    instrument_type: 'agency_rule',
    bill_number: null,
    enacted_date: '2025-06-30',
    effective_date: '2025-09-01',
    status: 'in_force',
    superseded_by: null,
    categories: ['algorithmic_accountability', 'individual_rights'],
    primary_category: 'individual_rights',
    scope: 'comprehensive',
    who_regulated: ['both'],
    provisions: {
      ai_interaction_disclosure: false, training_data_disclosure: false, content_labelling: false,
      risk_classification_system: false, impact_assessment_required: true, anti_discrimination: false,
      anti_discrimination_standard: null, human_review_right: false, opt_out_right: true,
      biometric_protection: false, voice_likeness_protection: false, data_rights_re_training: false,
      private_right_of_action: false, safe_harbor: false, prohibited_categories: false,
      agentic_ai_addressed: false, algorithmic_pricing_addressed: false, training_data_compensation: false,
    },
    enforcement_body: ['Data Protection Board of India'],
    max_penalty: '₹250 crore (~$30M USD) per data protection board order',
    max_penalty_usd_approx: 30000000,
    preemption_status: 'n/a',
    preemption_notes: null,
    legal_family: 'hybrid',
    inspired_by: ['in-in-dpdpa-2023', 'eu-eu-gdpr-2016'],
    influenced: [],
    official_text_url: 'https://www.meity.gov.in/digital-personal-data-protection-act',
    summary_url: null,
    last_verified: '2026-04-24',
    summary: 'Implementing rules under India\'s 2023 DPDPA establishing specific compliance requirements for significant data fiduciaries (large-scale data processors). Rules specify consent notice formats, data protection officer qualifications, data impact assessment requirements, and Data Protection Board procedure. AI systems used by significant data fiduciaries must comply with assessment requirements.',
    notable: 'Rules complete the DPDPA framework. AI developers operating at scale in India qualify as significant data fiduciaries and face enhanced obligations.',
    legal_citation: 'Digital Personal Data Protection Rules, 2025, MeitY Notification S.O. 2025',
    topics: ['data fiduciary AI obligations', 'significant data fiduciary AI', 'India AI compliance', 'data impact assessment', 'consent notice AI'],
    sector_tags: ['all_sectors', 'financial_services', 'healthcare', 'government_services'],
    technology_tags: ['decision_support_systems', 'predictive_analytics', 'generative_ai', 'biometric_data'],
    key_obligations: ['Significant data fiduciaries must appoint data protection officer', 'Conduct data protection impact assessments for high-risk processing', 'Specified consent notice format and language requirements', 'Audit and algorithmic assessment by independent data auditor annually', 'Implement privacy by design mechanisms in AI systems'],
  },
]

// ─── Main processing ──────────────────────────────────────────────────────────

// Add metadata to existing entries
const updated = src.map((law: Record<string, unknown>) => {
  const id = law.id as string
  const meta = META[id]
  if (!meta) {
    console.warn(`[WARN] No metadata for: ${id} — using placeholder`)
    return {
      ...law,
      legal_citation: `[Citation pending verification] — ${law.short_name}`,
      topics: [],
      sector_tags: ['all_sectors'],
      technology_tags: [],
      key_obligations: [],
    }
  }
  return { ...law, ...meta }
})

// Append new laws (skip if already in corpus)
const existingIds = new Set(src.map((l: Record<string, unknown>) => l.id))
const newToAdd = NEW_LAWS.filter(l => !existingIds.has(l.id))
console.log(`Adding ${newToAdd.length} new laws to corpus`)

const result = [...updated, ...newToAdd]

writeFileSync(join(ROOT, 'data/regulations.json'), JSON.stringify(result, null, 2))
console.log(`\nDone. Corpus: ${result.length} laws (was ${src.length})`)
console.log('Run: npm run validate')
