#!/usr/bin/env python3
"""
add-missing-records.py
Adds new records identified in the May 2026 coverage audit.
Run once: python3 scripts/add-missing-records.py
"""
import json
from datetime import date

PROJECT_ROOT = '/Users/art/Desktop/claude-projects/ai-regulation-db'
REGS_PATH = f'{PROJECT_ROOT}/data/regulations.json'
TODAY = date.today().isoformat()

def p(overrides=None):
    """Default provisions block."""
    base = {
        "ai_interaction_disclosure": False,
        "training_data_disclosure": False,
        "content_labelling": False,
        "risk_classification_system": False,
        "impact_assessment_required": False,
        "anti_discrimination": False,
        "anti_discrimination_standard": None,
        "human_review_right": False,
        "opt_out_right": False,
        "biometric_protection": False,
        "voice_likeness_protection": False,
        "data_rights_re_training": False,
        "private_right_of_action": False,
        "safe_harbor": False,
        "prohibited_categories": False,
        "agentic_ai_addressed": False,
        "algorithmic_pricing_addressed": False,
        "training_data_compensation": False,
    }
    if overrides:
        base.update(overrides)
    return base

NEW_RECORDS = [

# ──────────────────────────────────────────────────────────────
# CALIFORNIA 2024 — seven enacted AI laws (signed Sep 2024)
# ──────────────────────────────────────────────────────────────

{
    "id": "us-ca-ab2655-2024",
    "jurisdiction": "California",
    "jurisdiction_type": "subnational",
    "region": "US-CA",
    "country": "United States",
    "short_name": "California AB 2655 (Defending Democracy from Deepfake Deception Act)",
    "full_name": "Defending Democracy from Deepfake Deception Act of 2024",
    "instrument_type": "statute",
    "bill_number": "AB 2655",
    "enacted_date": "2024-09-17",
    "effective_date": "2025-01-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "synthetic_media",
    "categories": ["synthetic_media", "elections"],
    "scope": "sector_specific",
    "who_regulated": ["deployers", "platforms"],
    "provisions": p({"content_labelling": True, "prohibited_categories": True}),
    "enforcement_body": ["California courts (civil)"],
    "max_penalty": "Injunctive relief; civil damages",
    "max_penalty_usd_approx": None,
    "preemption_status": "low_risk",
    "preemption_notes": None,
    "legal_family": "us_consumer_protection",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240AB2655",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Requires large online platforms to label AI-generated content depicting political candidates or measures within 120 days of an election. Prohibits platforms from distributing materially deceptive AI-generated images or audio of candidates that did not actually make the depicted statements. Platforms must add disclosure labels and may be ordered to remove unlabeled deepfakes.",
    "notable": "Platform-facing law; pairs with AB 2839 (individual liability) for a two-track California election deepfake regime.",
    "legal_citation": "Cal. Elec. Code §§ 20012–20013 (as added); AB 2655, 2023–24 Leg. Sess.",
    "topics": ["election deepfakes", "AI-generated political content", "platform disclosure", "synthetic media elections"],
    "sector_tags": ["elections", "social_media"],
    "technology_tags": ["deepfake", "image_synthesis", "audio_synthesis", "generative_ai"],
    "key_obligations": [
        "Large platforms must label AI-generated election content within 72 hours of being notified",
        "Platforms must maintain mechanisms for candidates and campaigns to report unlabeled deepfakes",
        "Applies within 120 days before an election",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "us-ca-sb1120-2024",
    "jurisdiction": "California",
    "jurisdiction_type": "subnational",
    "region": "US-CA",
    "country": "United States",
    "short_name": "California SB 1120 (Health Insurance AI Utilization Review)",
    "full_name": "Physicians Make Decisions Act",
    "instrument_type": "statute",
    "bill_number": "SB 1120",
    "enacted_date": "2024-09-28",
    "effective_date": "2025-01-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "sector_healthcare",
    "categories": ["sector_healthcare", "algorithmic_systems"],
    "scope": "sector_specific",
    "who_regulated": ["deployers"],
    "provisions": p({"human_review_right": True, "impact_assessment_required": False}),
    "enforcement_body": ["California Department of Managed Health Care", "California Insurance Commissioner"],
    "max_penalty": "Administrative penalties; license actions",
    "max_penalty_usd_approx": None,
    "preemption_status": "low_risk",
    "preemption_notes": None,
    "legal_family": "us_consumer_protection",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB1120",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Prohibits health insurers and managed care plans from using AI or algorithms as the sole basis for denying, delaying, or modifying health care coverage decisions. Requires that any coverage determination made or assisted by AI must be reviewed and approved by a licensed California physician or appropriate health care provider. Applies to utilization review processes.",
    "notable": "First California law directly restricting AI in health insurance coverage decisions; part of a national trend of state healthcare AI bills.",
    "legal_citation": "Cal. Health & Saf. Code § 1367.01 (as amended); Cal. Ins. Code § 10123.135 (as added); SB 1120, 2023–24 Leg. Sess.",
    "topics": ["health insurance AI", "utilization review AI", "physician override AI", "algorithmic coverage decisions"],
    "sector_tags": ["healthcare", "insurance"],
    "technology_tags": ["algorithmic_decision_making", "clinical_ai"],
    "key_obligations": [
        "AI-assisted coverage decisions must be reviewed and signed off by a licensed physician",
        "Insurers must document AI involvement in utilization review decisions",
        "Patients retain rights to appeal AI-influenced denials through standard grievance procedures",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "us-ca-ab2839-2024",
    "jurisdiction": "California",
    "jurisdiction_type": "subnational",
    "region": "US-CA",
    "country": "United States",
    "short_name": "California AB 2839 (Election Deepfakes — Individual Liability)",
    "full_name": "Elections: Deceptive AI Content",
    "instrument_type": "statute",
    "bill_number": "AB 2839",
    "enacted_date": "2024-09-17",
    "effective_date": "2024-09-17",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "synthetic_media",
    "categories": ["synthetic_media", "elections"],
    "scope": "sector_specific",
    "who_regulated": ["individuals", "deployers"],
    "provisions": p({"content_labelling": True, "prohibited_categories": True, "private_right_of_action": True}),
    "enforcement_body": ["California courts (civil)"],
    "max_penalty": "Actual damages; statutory damages up to $25,000 per violation; injunctive relief",
    "max_penalty_usd_approx": 25000,
    "preemption_status": "low_risk",
    "preemption_notes": None,
    "legal_family": "us_consumer_protection",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240AB2839",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Prohibits distributing materially deceptive AI-generated images, audio, or video depicting candidates for office or election officials within 120 days of an election without a clear disclosure. Creates a private right of action for candidates, election officials, and the Attorney General. Enacted as urgency statute, effective immediately on signing.",
    "notable": "Urgency statute; companion to AB 2655 (platform obligations). Individual-level liability for election deepfakes.",
    "legal_citation": "Cal. Elec. Code §§ 20010–20011 (as added); AB 2839, 2023–24 Leg. Sess.",
    "topics": ["election deepfakes", "synthetic media elections", "AI political disinformation", "individual liability deepfakes"],
    "sector_tags": ["elections"],
    "technology_tags": ["deepfake", "image_synthesis", "audio_synthesis", "video_synthesis"],
    "key_obligations": [
        "Must include clear disclosure when distributing AI-generated election content",
        "Prohibition on materially deceptive deepfakes of candidates within 120-day election window",
        "Candidates and AG may seek injunctions and damages",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "us-ca-ab2355-2024",
    "jurisdiction": "California",
    "jurisdiction_type": "subnational",
    "region": "US-CA",
    "country": "United States",
    "short_name": "California AB 2355 (Political Ad AI Disclosure)",
    "full_name": "Political Advertisements: Artificial Intelligence Disclosures",
    "instrument_type": "statute",
    "bill_number": "AB 2355",
    "enacted_date": "2024-09-19",
    "effective_date": "2025-01-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "synthetic_media",
    "categories": ["synthetic_media", "elections"],
    "scope": "sector_specific",
    "who_regulated": ["deployers", "individuals"],
    "provisions": p({"content_labelling": True, "ai_interaction_disclosure": True}),
    "enforcement_body": ["California Fair Political Practices Commission"],
    "max_penalty": "Administrative fines; civil penalties",
    "max_penalty_usd_approx": None,
    "preemption_status": "low_risk",
    "preemption_notes": None,
    "legal_family": "us_consumer_protection",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240AB2355",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Requires political advertisements that include AI-generated content to include a clear and conspicuous disclosure stating the content was created or substantially altered using AI. Applies to paid political advertisements in any medium. Enforced by the California Fair Political Practices Commission.",
    "notable": "Extends California's existing political ad disclosure regime to cover AI-generated content specifically.",
    "legal_citation": "Cal. Gov. Code § 84504.3 (as added); AB 2355, 2023–24 Leg. Sess.",
    "topics": ["political advertising AI", "AI disclosure elections", "campaign finance AI", "synthetic media disclosure"],
    "sector_tags": ["elections", "advertising"],
    "technology_tags": ["generative_ai", "deepfake"],
    "key_obligations": [
        "Political ads using AI-generated content must include conspicuous disclosure",
        "Applies to any paid political communication in any medium",
        "FPPC to adopt implementing regulations",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "us-ca-ab1831-2024",
    "jurisdiction": "California",
    "jurisdiction_type": "subnational",
    "region": "US-CA",
    "country": "United States",
    "short_name": "California AB 1831 (AI-Generated CSAM)",
    "full_name": "Child Sexual Abuse Material: Artificial Intelligence",
    "instrument_type": "statute",
    "bill_number": "AB 1831",
    "enacted_date": "2024-09-17",
    "effective_date": "2025-01-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "child_safety",
    "categories": ["child_safety", "synthetic_media"],
    "scope": "sector_specific",
    "who_regulated": ["individuals"],
    "provisions": p({"prohibited_categories": True}),
    "enforcement_body": ["California courts (criminal)", "California Attorney General"],
    "max_penalty": "Felony; imprisonment up to 8 years",
    "max_penalty_usd_approx": None,
    "preemption_status": "low_risk",
    "preemption_notes": None,
    "legal_family": "us_consumer_protection",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240AB1831",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Expands California's child sexual abuse material (CSAM) laws to expressly cover AI-generated, computer-generated, or otherwise digitally created depictions of minors engaged in sexual conduct. Makes it a felony to possess, distribute, or produce such material regardless of whether any real child is depicted.",
    "notable": "Closes the AI-generated CSAM loophole in California law; part of a wave of similar state laws in 2024.",
    "legal_citation": "Cal. Penal Code § 311 et seq. (as amended); AB 1831, 2023–24 Leg. Sess.",
    "topics": ["AI CSAM", "synthetic child abuse material", "AI-generated illegal content", "child protection AI"],
    "sector_tags": ["law_enforcement", "child_safety"],
    "technology_tags": ["generative_ai", "image_synthesis", "video_synthesis"],
    "key_obligations": [
        "Prohibition on possessing, producing, or distributing AI-generated CSAM",
        "No requirement of a real minor victim for prosecution",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "us-ca-sb926-2024",
    "jurisdiction": "California",
    "jurisdiction_type": "subnational",
    "region": "US-CA",
    "country": "United States",
    "short_name": "California SB 926 (AI Nonconsensual Intimate Imagery)",
    "full_name": "Artificial Intelligence: Intimate Images",
    "instrument_type": "statute",
    "bill_number": "SB 926",
    "enacted_date": "2024-09-19",
    "effective_date": "2025-01-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "synthetic_media",
    "categories": ["synthetic_media", "privacy"],
    "scope": "sector_specific",
    "who_regulated": ["individuals"],
    "provisions": p({"prohibited_categories": True, "private_right_of_action": True}),
    "enforcement_body": ["California courts (criminal and civil)"],
    "max_penalty": "Misdemeanor or felony; civil damages",
    "max_penalty_usd_approx": None,
    "preemption_status": "low_risk",
    "preemption_notes": None,
    "legal_family": "us_consumer_protection",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB926",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Expands California's nonconsensual intimate imagery (NCII) law to cover AI-generated or digitally altered intimate images of real, identifiable persons. Creates both criminal liability (misdemeanor/felony depending on intent) and a private civil right of action for victims. Addresses sextortion using AI-generated imagery.",
    "notable": "Extends existing revenge porn law to cover synthetic deepfakes of real people. Companion to SB 981 (platform reporting obligations).",
    "legal_citation": "Cal. Penal Code § 647(j)(4) (as amended); Cal. Civ. Code § 1708.87 (as amended); SB 926, 2023–24 Leg. Sess.",
    "topics": ["AI intimate images", "deepfake NCII", "nonconsensual pornography AI", "sextortion AI"],
    "sector_tags": ["law_enforcement"],
    "technology_tags": ["deepfake", "image_synthesis", "video_synthesis", "generative_ai"],
    "key_obligations": [
        "Prohibits distributing AI-generated intimate images of identifiable real persons without consent",
        "Criminal and civil liability for perpetrators",
        "Victims may seek injunctive relief and actual damages",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "us-ca-sb981-2024",
    "jurisdiction": "California",
    "jurisdiction_type": "subnational",
    "region": "US-CA",
    "country": "United States",
    "short_name": "California SB 981 (Deepfake Intimate Image Reporting — Platforms)",
    "full_name": "Social Media Platforms: Artificial Intelligence-Generated Content",
    "instrument_type": "statute",
    "bill_number": "SB 981",
    "enacted_date": "2024-09-19",
    "effective_date": "2025-01-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "synthetic_media",
    "categories": ["synthetic_media", "platform_regulation"],
    "scope": "sector_specific",
    "who_regulated": ["platforms"],
    "provisions": p({"content_labelling": False}),
    "enforcement_body": ["California Attorney General", "California courts (civil)"],
    "max_penalty": "Civil penalties up to $1,000 per violation",
    "max_penalty_usd_approx": 1000,
    "preemption_status": "low_risk",
    "preemption_notes": None,
    "legal_family": "us_consumer_protection",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB981",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Requires large social media platforms to implement a mechanism allowing users to report sexually explicit AI-generated or digitally altered content depicting real people without their consent. Platforms must provide an easily accessible reporting tool and take action on valid reports. Complements SB 926 by imposing platform-level obligations.",
    "notable": "Platform-side obligation for AI NCII; pairs with SB 926 (individual liability). Early example of platform duty-to-act requirements for AI-generated harmful content.",
    "legal_citation": "Cal. Bus. & Prof. Code § 22949.30 (as added); SB 981, 2023–24 Leg. Sess.",
    "topics": ["platform NCII reporting", "deepfake reporting mechanism", "AI intimate image platforms", "social media AI obligations"],
    "sector_tags": ["social_media", "platforms"],
    "technology_tags": ["deepfake", "image_synthesis", "generative_ai"],
    "key_obligations": [
        "Large social media platforms must provide user-accessible reporting tool for AI-generated sexually explicit content",
        "Platforms must act on valid reports within a reasonable timeframe",
        "Platform must publish an annual transparency report on NCII reports received and actions taken",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

# ──────────────────────────────────────────────────────────────
# JAPAN — statutory instruments under the AI Promotion Act
# ──────────────────────────────────────────────────────────────

{
    "id": "jp-jp-aiutilguidelines-2025",
    "jurisdiction": "Japan",
    "jurisdiction_type": "national",
    "region": "JP",
    "country": "Japan",
    "short_name": "Japan AI Utilization Guidelines (2025)",
    "full_name": "Guidelines on the Utilization of Artificial Intelligence (Article 13 Guidelines)",
    "instrument_type": "guidelines",
    "bill_number": None,
    "enacted_date": "2025-12-19",
    "effective_date": "2025-12-19",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["developers", "deployers", "government_agencies"],
    "provisions": p({"impact_assessment_required": True, "ai_interaction_disclosure": True}),
    "enforcement_body": ["AI Strategy Headquarters (Cabinet)", "METI", "Ministry of Internal Affairs and Communications"],
    "max_penalty": "Administrative guidance; sector-specific enforcement via existing laws",
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "hybrid",
    "inspired_by": ["jp-jp-aiprom-2025"],
    "influenced": [],
    "official_text_url": "https://www.cas.go.jp/jp/seisaku/ai_senryaku/index.html",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Statutory guidelines issued by the government pursuant to Article 13 of Japan's AI Promotion Act (2025). Establish operational standards for responsible AI development and utilization across sectors, covering transparency, accountability, safety evaluation, and human oversight. Provide sector-specific guidance for high-risk AI applications in healthcare, finance, and transportation. Issued by the AI Strategy Headquarters on December 19, 2025.",
    "notable": "First statutory AI utilization guidelines issued under Japan's AI Promotion Act; operationalize the Act's principles with sector-specific detail.",
    "legal_citation": "Guidelines on AI Utilization under Art. 13 of Act No. 14 of 2025 (Japan); promulgated December 19, 2025.",
    "topics": ["Japan AI guidelines", "AI utilization standards", "responsible AI Japan", "AI safety evaluation Japan"],
    "sector_tags": ["all_sectors"],
    "technology_tags": ["generative_ai", "large_language_models", "autonomous_systems"],
    "key_obligations": [
        "AI developers must implement safety evaluation processes aligned with government guidelines",
        "Deployers must document AI system purpose, risks, and oversight mechanisms",
        "Transparency obligations for AI interactions in consumer-facing applications",
        "Sector ministries to issue supplementary guidance for high-risk domains",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "jp-jp-aibasicplan-2025",
    "jurisdiction": "Japan",
    "jurisdiction_type": "national",
    "region": "JP",
    "country": "Japan",
    "short_name": "Japan Basic AI Plan (2025)",
    "full_name": "Basic Plan on the Promotion of Research, Development and Utilization of AI-Related Technologies",
    "instrument_type": "policy_framework",
    "bill_number": None,
    "enacted_date": "2025-12-23",
    "effective_date": "2025-12-23",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p({"risk_classification_system": True, "impact_assessment_required": True}),
    "enforcement_body": ["AI Strategy Headquarters (Cabinet)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "hybrid",
    "inspired_by": ["jp-jp-aiprom-2025"],
    "influenced": [],
    "official_text_url": "https://www.cas.go.jp/jp/seisaku/ai_senryaku/index.html",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Cabinet-approved Basic Plan issued pursuant to Article 18 of Japan's AI Promotion Act (2025). Sets out the government's multi-year strategic priorities for AI research, development, and deployment. Specifies measurable targets for AI investment, talent development, international cooperation, and AI safety. Binding on all government ministries, which must align their sectoral AI policies and budgets with the Plan. Approved by the AI Strategy Headquarters on December 23, 2025.",
    "notable": "The core planning instrument under Japan's AI Promotion Act; binds all ministries and establishes the national AI investment roadmap.",
    "legal_citation": "Basic Plan under Art. 18 of Act No. 14 of 2025 (Japan); Cabinet approval December 23, 2025.",
    "topics": ["Japan national AI plan", "AI investment Japan", "AI strategy headquarters", "Japan AI roadmap"],
    "sector_tags": ["all_sectors", "government_services"],
    "technology_tags": ["generative_ai", "large_language_models"],
    "key_obligations": [
        "All government ministries must align sectoral AI policies and budgets with the Basic Plan",
        "Annual progress reports to the Cabinet on Plan implementation",
        "AI Strategy Headquarters to coordinate cross-ministry AI initiatives",
        "International AI governance engagement obligations tied to G7/OECD commitments",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

# ──────────────────────────────────────────────────────────────
# AUSTRALIA — National AI Plan (Dec 2025)
# ──────────────────────────────────────────────────────────────

{
    "id": "au-au-naianplan-2025",
    "jurisdiction": "Australia",
    "jurisdiction_type": "national",
    "region": "Asia-Pacific",
    "country": "Australia",
    "short_name": "Australia National AI Plan 2025",
    "full_name": "Australia's National Artificial Intelligence Plan 2025",
    "instrument_type": "policy_framework",
    "bill_number": None,
    "enacted_date": "2025-12-02",
    "effective_date": "2025-12-02",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p({"risk_classification_system": True, "impact_assessment_required": True}),
    "enforcement_body": ["Department of Industry, Science and Resources", "National AI Centre (NAIC)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "standalone",
    "inspired_by": ["au-au-naistrategy-2021"],
    "influenced": [],
    "official_text_url": "https://www.industry.gov.au/publications/australias-national-ai-plan",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Australia's whole-of-government AI strategy through 2030, superseding the 2021 National AI Strategy. Establishes the government's AI investment priorities, safety and governance framework, and international engagement positions. Commits to mandatory safeguards for high-risk AI applications in regulated sectors, builds on the 2024 Voluntary AI Safety Standard, and establishes a National AI Centre as the coordination body. Endorsed by the Albanese government December 2, 2025.",
    "notable": "Supersedes au-au-naistrategy-2021; signals shift from voluntary to mandatory high-risk AI obligations in Australia.",
    "legal_citation": "Australia's National AI Plan 2025, released December 2, 2025 by the Department of Industry, Science and Resources.",
    "topics": ["Australia AI plan", "national AI strategy Australia", "AI safety standard Australia", "Australia AI governance 2030"],
    "sector_tags": ["all_sectors", "government_services"],
    "technology_tags": ["generative_ai", "autonomous_systems"],
    "key_obligations": [
        "Government agencies must apply mandatory AI safety standards for high-risk AI procurement",
        "Mandatory reporting for high-risk AI incidents in regulated sectors",
        "All Commonwealth entities to publish AI transparency statements by 2026",
        "Establish mandatory high-risk AI regime with statutory basis by 2027",
    ],
    "ai_specific": True,
    "instrument_binding": False,
    "text_path": None,
    "operative_dates": None,
},

# ──────────────────────────────────────────────────────────────
# SINGAPORE — Model AI Governance Framework for Agentic AI
# ──────────────────────────────────────────────────────────────

{
    "id": "sg-sg-agenticaigf-2026",
    "jurisdiction": "Singapore",
    "jurisdiction_type": "national",
    "region": "Asia-Pacific",
    "country": "Singapore",
    "short_name": "Singapore Model AI Governance Framework for Agentic AI",
    "full_name": "Model AI Governance Framework for Agentic AI Systems",
    "instrument_type": "guidelines",
    "bill_number": None,
    "enacted_date": "2026-01-01",
    "effective_date": "2026-01-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["developers", "deployers"],
    "provisions": p({"agentic_ai_addressed": True, "impact_assessment_required": True, "human_review_right": True}),
    "enforcement_body": ["Infocomm Media Development Authority (IMDA)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "standalone",
    "inspired_by": ["sg-sg-maigf-2020"],
    "influenced": [],
    "official_text_url": "https://www.imda.gov.sg/resources/press-releases-factsheets-and-speeches/factsheets/2026/model-ai-governance-framework-agentic-ai",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Singapore's first dedicated governance framework for agentic AI systems — AI that can autonomously plan, execute multi-step tasks, and interact with other AI agents or external systems. Published by IMDA and the AI Verify Foundation in January 2026. Addresses unique risks of agentic AI including unpredictable behavior, cascading failures in multi-agent pipelines, and reduced human oversight. Provides a five-layer accountability model covering principal hierarchy, agent transparency, human control mechanisms, and incident response.",
    "notable": "First major national governance framework specifically targeting agentic AI. Builds on Singapore's 2020 MAIGF and positions Singapore as the global reference for agentic AI governance.",
    "legal_citation": "Model AI Governance Framework for Agentic AI Systems, IMDA / AI Verify Foundation, January 2026.",
    "topics": ["agentic AI governance", "multi-agent systems", "autonomous AI Singapore", "AI agent accountability"],
    "sector_tags": ["all_sectors"],
    "technology_tags": ["agentic_ai", "large_language_models", "multi_agent_systems", "autonomous_systems"],
    "key_obligations": [
        "Organizations deploying agentic AI must establish a principal hierarchy with clear human override mechanisms",
        "Agentic AI systems must maintain action logs sufficient for post-hoc accountability",
        "Human review required for high-stakes agentic decisions (financial, legal, medical)",
        "Multi-agent pipelines must designate a responsible entity for overall system behavior",
    ],
    "ai_specific": True,
    "instrument_binding": False,
    "text_path": None,
    "operative_dates": None,
},

# ──────────────────────────────────────────────────────────────
# SPAIN — Royal Decree 729/2023 (AESIA)
# ──────────────────────────────────────────────────────────────

{
    "id": "es-es-aesia-2023",
    "jurisdiction": "Spain",
    "jurisdiction_type": "national",
    "region": "Europe",
    "country": "Spain",
    "short_name": "Spain Royal Decree 729/2023 (AESIA)",
    "full_name": "Real Decreto 729/2023 por el que se crea la Agencia Española de Supervisión de la Inteligencia Artificial",
    "instrument_type": "executive_order",
    "bill_number": None,
    "enacted_date": "2023-07-22",
    "effective_date": "2023-09-02",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies"],
    "provisions": p(),
    "enforcement_body": ["AESIA (Agencia Española de Supervisión de la Inteligencia Artificial)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "civil_law",
    "inspired_by": ["eu-eu-aiact-2024"],
    "influenced": [],
    "official_text_url": "https://www.boe.es/diario_boe/txt.php?id=BOE-A-2023-17694",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Royal Decree establishing the Agencia Española de Supervisión de la Inteligencia Artificial (AESIA) as Spain's national AI supervisory authority. AESIA is responsible for supervising the application of the EU AI Act in Spain, conducting market surveillance, handling complaints, and representing Spain in EU AI governance bodies. Spain was the first EU member state to establish a dedicated national AI supervisory authority. Located in A Coruña (Galicia). AESIA is separate from the AI regulatory sandbox (established by RD 817/2023).",
    "notable": "Spain was the first EU country to designate its EU AI Act national competent authority, ahead of the Act's full application. AESIA became operational in late 2023.",
    "legal_citation": "Real Decreto 729/2023, de 22 de julio (BOE núm. 175, 24 julio 2023).",
    "topics": ["AESIA Spain", "Spain AI supervisory authority", "EU AI Act national authority Spain", "Spanish AI regulator"],
    "sector_tags": ["all_sectors", "government_services"],
    "technology_tags": ["general_ai"],
    "key_obligations": [
        "AESIA to serve as Spain's national competent authority and market surveillance authority for EU AI Act",
        "AESIA to establish national AI registry and complaint handling mechanisms",
        "AESIA to represent Spain at EU AI Board",
        "Budget and staffing under Ministry of Economic Affairs and Digital Transformation",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

# ──────────────────────────────────────────────────────────────
# DIFC — 2024 AI Amendments to Data Protection Regulations
# ──────────────────────────────────────────────────────────────

{
    "id": "ae-difc-dpr2024-2024",
    "jurisdiction": "UAE — DIFC",
    "jurisdiction_type": "subnational",
    "region": "Middle East",
    "country": "United Arab Emirates",
    "short_name": "DIFC DPR 2024 AI Amendments",
    "full_name": "DIFC Data Protection Regulations 2024 — AI System Amendments",
    "instrument_type": "regulation",
    "bill_number": None,
    "enacted_date": "2024-09-01",
    "effective_date": "2024-09-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "data_protection",
    "categories": ["data_protection", "algorithmic_systems"],
    "scope": "comprehensive",
    "who_regulated": ["developers", "deployers"],
    "provisions": p({
        "risk_classification_system": True,
        "impact_assessment_required": True,
        "human_review_right": True,
        "agentic_ai_addressed": True,
    }),
    "enforcement_body": ["DIFC Commissioner of Data Protection"],
    "max_penalty": "USD 100,000 per violation",
    "max_penalty_usd_approx": 100000,
    "preemption_status": "n/a",
    "preemption_notes": "DIFC is a separate free zone with its own legal system; these regulations apply only within the DIFC.",
    "legal_family": "civil_law",
    "inspired_by": ["ae-difc-reg10-2020"],
    "influenced": [],
    "official_text_url": "https://www.difc.ae/business/operating/data-protection/",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Amendments to the DIFC Data Protection Regulations introducing new Chapter 5A on AI Systems. Adds requirements for AI system design principles (ethicality, fairness, transparency, security, accountability), mandatory AI system audits and certification for high-risk AI, restrictions on AI processing of sensitive personal data, and obligations for autonomous decision-making systems. These amendments supplement the Autonomous Systems Regulation (Regulation 10, September 2023). Full enforcement commenced January 2026.",
    "notable": "Extends DIFC's world-leading autonomous systems regulation with sector-specific AI governance requirements. DIFC continues to position itself as the most comprehensive AI regulatory jurisdiction in the Gulf.",
    "legal_citation": "DIFC Data Protection Regulations 2024, Chapter 5A; Commissioner's Notice 2024/01; effective September 1, 2024.",
    "topics": ["DIFC AI regulation", "autonomous systems DIFC", "AI audit DIFC", "Gulf AI governance"],
    "sector_tags": ["financial_services", "all_sectors"],
    "technology_tags": ["algorithmic_decision_making", "autonomous_systems", "generative_ai"],
    "key_obligations": [
        "AI systems processing personal data must meet ethicality, fairness, transparency, security, and accountability design principles",
        "High-risk AI systems require third-party audit and certification before deployment",
        "Data controllers must maintain an AI system register",
        "Automated decisions with significant effects on individuals require human review upon request",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

# ──────────────────────────────────────────────────────────────
# LATVIA — Law on Development of AI
# ──────────────────────────────────────────────────────────────

{
    "id": "lv-lv-aidev-2025",
    "jurisdiction": "Latvia",
    "jurisdiction_type": "national",
    "region": "Europe",
    "country": "Latvia",
    "short_name": "Latvia Law on the Development of Artificial Intelligence",
    "full_name": "Likums par mākslīgā intelekta attīstību (Law on the Development of Artificial Intelligence)",
    "instrument_type": "statute",
    "bill_number": None,
    "enacted_date": "2025-01-01",
    "effective_date": "2025-01-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["developers", "deployers", "government_agencies"],
    "provisions": p({"risk_classification_system": True, "impact_assessment_required": True}),
    "enforcement_body": ["Latvia AI Centre (established by companion law)", "Data State Inspectorate"],
    "max_penalty": "Administrative fines per EU AI Act enforcement mechanism",
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "civil_law",
    "inspired_by": ["eu-eu-aiact-2024"],
    "influenced": [],
    "official_text_url": "https://likumi.lv/ta/id/",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Latvia's primary national AI governance law, establishing principles and a framework for responsible AI development and deployment in Latvia. Sets out human-centric AI development principles, transparency and accountability requirements, and Latvia's implementation framework for the EU AI Act. Enacted alongside the companion Law on the AI Centre (lv-lv-aicentre-2025), which establishes the institutional body. Latvia became one of the first EU member states to adopt national AI legislation supplementing the EU AI Act.",
    "notable": "Latvia was among the first EU member states to enact comprehensive national AI legislation alongside EU AI Act implementation. Paired with the AI Centre law.",
    "legal_citation": "Likums par mākslīgā intelekta attīstību, Latvijas Vēstnesis, 2025.",
    "topics": ["Latvia AI law", "national AI legislation Latvia", "EU AI Act implementation Latvia", "Baltic AI governance"],
    "sector_tags": ["all_sectors"],
    "technology_tags": ["general_ai", "generative_ai"],
    "key_obligations": [
        "AI developers and deployers must adhere to human-centric development principles",
        "High-risk AI systems subject to mandatory registration and conformity assessment",
        "Government agencies must conduct AI impact assessments before deployment",
        "Latvia AI Centre designated as national competent authority",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

# ──────────────────────────────────────────────────────────────
# AFRICA — National AI strategies
# ──────────────────────────────────────────────────────────────

{
    "id": "rw-rw-naip-2023",
    "jurisdiction": "Rwanda",
    "jurisdiction_type": "national",
    "region": "Africa",
    "country": "Rwanda",
    "short_name": "Rwanda National AI Policy 2023",
    "full_name": "Rwanda National Artificial Intelligence Policy",
    "instrument_type": "policy_framework",
    "bill_number": None,
    "enacted_date": "2023-04-20",
    "effective_date": "2023-04-20",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p(),
    "enforcement_body": ["Ministry of ICT and Innovation", "Rwanda Utilities Regulatory Authority (RURA)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "standalone",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://www.minict.gov.rw/fileadmin/user_upload/Rwanda_National_AI_Policy.pdf",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Rwanda's first national AI policy, approved by the Cabinet on April 20, 2023, making Rwanda the first African country to adopt a national AI policy. Establishes Rwanda's vision for AI-driven economic transformation and public service delivery across agriculture, health, education, and justice. Focuses on responsible AI development, data governance, AI talent development, and international AI cooperation. The policy commits Rwanda to human-centric AI aligned with African Union principles.",
    "notable": "First African country to adopt a formal national AI policy; a landmark for the continent.",
    "legal_citation": "Rwanda National Artificial Intelligence Policy, Cabinet approval April 20, 2023.",
    "topics": ["Rwanda AI policy", "Africa AI governance", "first African AI policy", "national AI strategy Rwanda"],
    "sector_tags": ["all_sectors", "government_services"],
    "technology_tags": ["general_ai"],
    "key_obligations": [
        "Government to establish AI governance coordination mechanism",
        "Public sector to adopt responsible AI procurement standards",
        "Investment in national AI talent and research capacity",
        "Data governance framework to support AI development",
    ],
    "ai_specific": True,
    "instrument_binding": False,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "ke-ke-aistrategy-2025",
    "jurisdiction": "Kenya",
    "jurisdiction_type": "national",
    "region": "Africa",
    "country": "Kenya",
    "short_name": "Kenya National AI Strategy 2025–2030",
    "full_name": "Kenya National Artificial Intelligence Strategy 2025–2030",
    "instrument_type": "policy_framework",
    "bill_number": None,
    "enacted_date": "2025-03-27",
    "effective_date": "2025-03-27",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p(),
    "enforcement_body": ["Ministry of Information, Communications and the Digital Economy", "Konza Technopolis Development Authority"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "standalone",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://ict.go.ke/national-ai-strategy-2025-2030/",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Kenya's five-year national AI strategy, formally launched March 27, 2025, positioning Kenya as East Africa's regional AI hub. Organized around seven pillars: AI infrastructure and data, talent development, research and innovation, ethical AI governance, public sector adoption, private sector transformation, and international partnerships. Commits Kenya to establishing an AI governance framework and a Centre of Excellence in AI by 2027. Includes specific targets for AI adoption in healthcare, agriculture, and financial services.",
    "notable": "Kenya positions itself as Africa's regional AI leader, particularly for the East Africa corridor. The Strategy was developed with UNESCO and World Bank support.",
    "legal_citation": "Kenya National AI Strategy 2025–2030, Ministry of ICT, March 27, 2025.",
    "topics": ["Kenya AI strategy", "East Africa AI", "Africa AI governance", "Kenya technology policy"],
    "sector_tags": ["all_sectors", "government_services"],
    "technology_tags": ["general_ai"],
    "key_obligations": [
        "Government to establish AI governance framework by 2026",
        "Public sector to publish AI deployment guidelines",
        "Investment in national AI research infrastructure and data centres",
        "Centre of Excellence in AI to be established by 2027",
    ],
    "ai_specific": True,
    "instrument_binding": False,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "ng-ng-nais-2024",
    "jurisdiction": "Nigeria",
    "jurisdiction_type": "national",
    "region": "Africa",
    "country": "Nigeria",
    "short_name": "Nigeria National AI Strategy (NAIS) 2024",
    "full_name": "Nigeria National Artificial Intelligence Strategy 2024–2029",
    "instrument_type": "policy_framework",
    "bill_number": None,
    "enacted_date": "2024-08-01",
    "effective_date": "2024-08-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p(),
    "enforcement_body": ["Federal Ministry of Communications, Innovation and Digital Economy", "NITDA (National Information Technology Development Agency)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "standalone",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://ncair.nitda.gov.ng/national-ai-strategy/",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Nigeria's five-year national AI strategy, launched August 2024 by the Federal Ministry of Communications, Innovation and Digital Economy. Establishes Nigeria's vision to become Africa's largest AI economy by leveraging its population of over 220 million and growing tech sector. Organized around five pillars: AI education and skills, AI-powered public services, AI innovation ecosystem, responsible AI governance, and international AI collaboration. Nigeria's National Centre for Artificial Intelligence and Robotics (NCAIR) under NITDA leads implementation.",
    "notable": "Nigeria has Africa's largest economy and population; this strategy positions it as the continental AI superpower. Implementation is anchored in the NDPA 2023 data governance framework.",
    "legal_citation": "Nigeria National Artificial Intelligence Strategy 2024–2029, NITDA/NCAIR, August 2024.",
    "topics": ["Nigeria AI strategy", "West Africa AI", "Africa AI governance", "NCAIR Nigeria"],
    "sector_tags": ["all_sectors"],
    "technology_tags": ["general_ai"],
    "key_obligations": [
        "NCAIR to publish national AI standards and guidelines by 2025",
        "Federal agencies to conduct AI readiness assessments",
        "Investment in AI education programs and STEM curriculum integration",
        "Annual AI governance progress reports to the President",
    ],
    "ai_specific": True,
    "instrument_binding": False,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "za-za-naipf-2024",
    "jurisdiction": "South Africa",
    "jurisdiction_type": "national",
    "region": "Africa",
    "country": "South Africa",
    "short_name": "South Africa National AI Policy Framework 2024",
    "full_name": "South Africa National Artificial Intelligence Policy Framework",
    "instrument_type": "policy_framework",
    "bill_number": None,
    "enacted_date": "2024-08-01",
    "effective_date": "2024-08-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p({"risk_classification_system": True}),
    "enforcement_body": ["Department of Communications and Digital Technologies (DCDT)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "standalone",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://www.dcdt.gov.za/sa-national-ai-policy-framework/",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "South Africa's National AI Policy Framework, published by the Department of Communications and Digital Technologies (DCDT) in August 2024. Establishes six pillars for responsible AI development: inclusive innovation, human-centred AI, responsible governance, data sovereignty, AI skills and education, and economic transformation. Introduces a risk-based approach to AI oversight aligned with international standards. The Framework preceded the formal draft National AI Policy published in April 2026 (which opened for public consultation). Applies to both public and private sector AI adoption.",
    "notable": "South Africa's first formal AI policy document; signals commitment to risk-based governance before formal legislation. Led to the April 2026 draft AI Policy published for consultation.",
    "legal_citation": "South Africa National AI Policy Framework, DCDT, August 2024.",
    "topics": ["South Africa AI policy", "Southern Africa AI", "Africa AI governance", "DCDT AI framework"],
    "sector_tags": ["all_sectors"],
    "technology_tags": ["general_ai"],
    "key_obligations": [
        "Government to develop sector-specific AI guidelines building on the framework",
        "Risk-based assessment of AI applications across sectors",
        "Data governance alignment with POPIA requirements",
        "Annual review of framework against international developments",
    ],
    "ai_specific": True,
    "instrument_binding": False,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "zw-zw-naistrategy-2026",
    "jurisdiction": "Zimbabwe",
    "jurisdiction_type": "national",
    "region": "Africa",
    "country": "Zimbabwe",
    "short_name": "Zimbabwe National AI Strategy 2026–2030",
    "full_name": "Zimbabwe National Artificial Intelligence Strategy 2026–2030",
    "instrument_type": "policy_framework",
    "bill_number": None,
    "enacted_date": "2026-03-13",
    "effective_date": "2026-03-13",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p(),
    "enforcement_body": ["Ministry of Information Communication Technology, Postal and Courier Services", "Postal and Telecommunications Regulatory Authority of Zimbabwe (POTRAZ)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "standalone",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://www.potraz.gov.zw/national-ai-strategy/",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Zimbabwe's first national AI strategy, launched by President Mnangagwa on March 13, 2026. Establishes Zimbabwe's vision for AI-driven inclusive digital transformation through 2030. Organized around four pillars: AI infrastructure and connectivity, AI skills and human capital, ethical and responsible AI governance, and AI-powered economic sectors (agriculture, mining, tourism, financial services). Cabinet-approved national instrument with implementation overseen by POTRAZ.",
    "notable": "Most recent African national AI strategy as of its launch; emphasizes Zimbabwe's natural resource sectors as AI adoption targets.",
    "legal_citation": "Zimbabwe National AI Strategy 2026–2030, Cabinet approval / launch March 13, 2026.",
    "topics": ["Zimbabwe AI strategy", "Southern Africa AI", "Africa AI governance", "Zimbabwe digital transformation"],
    "sector_tags": ["all_sectors", "government_services"],
    "technology_tags": ["general_ai"],
    "key_obligations": [
        "Government agencies to adopt AI policies aligned with the strategy by 2027",
        "Establishment of National AI Governance Council",
        "Investment in AI connectivity infrastructure in rural and peri-urban areas",
        "Sector ministries to develop AI action plans within 12 months of strategy launch",
    ],
    "ai_specific": True,
    "instrument_binding": False,
    "text_path": None,
    "operative_dates": None,
},

# ──────────────────────────────────────────────────────────────
# MIDDLE EAST — sector AI instruments
# ──────────────────────────────────────────────────────────────

{
    "id": "qa-qa-cbgai-2024",
    "jurisdiction": "Qatar",
    "jurisdiction_type": "national",
    "region": "Middle East",
    "country": "Qatar",
    "short_name": "Qatar Central Bank AI Guideline 2024",
    "full_name": "Qatar Central Bank Artificial Intelligence Guideline for Financial Institutions",
    "instrument_type": "regulation",
    "bill_number": None,
    "enacted_date": "2024-09-04",
    "effective_date": "2024-09-04",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "sector_financial",
    "categories": ["sector_financial", "general_ai_governance"],
    "scope": "sector_specific",
    "who_regulated": ["deployers"],
    "provisions": p({
        "risk_classification_system": True,
        "impact_assessment_required": True,
        "human_review_right": True,
    }),
    "enforcement_body": ["Qatar Central Bank (QCB)"],
    "max_penalty": "License revocation; regulatory sanctions; prior QCB approval withdrawal",
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "civil_law",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://www.qcb.gov.qa/",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Binding AI guideline issued by the Qatar Central Bank on September 4, 2024, mandatory for all QCB-licensed financial institutions. Requires licensed entities to develop an AI strategy, conduct AI risk assessments, implement human oversight protocols, and establish AI governance committees at board level. High-risk AI systems (credit scoring, fraud detection, customer authentication) require explicit QCB pre-approval before deployment. Sets minimum standards for AI model documentation, validation, and performance monitoring in the financial sector.",
    "notable": "One of the first binding sector-specific AI regulations in the Gulf region. Pre-approval requirement for high-risk financial AI is unusually stringent by regional standards.",
    "legal_citation": "Qatar Central Bank AI Guideline, issued pursuant to QCB Governor's Decision, September 4, 2024.",
    "topics": ["Qatar financial AI regulation", "Gulf banking AI", "QCB AI guideline", "financial sector AI governance Middle East"],
    "sector_tags": ["financial_services", "banking"],
    "technology_tags": ["algorithmic_decision_making", "credit_scoring_ai", "fraud_detection_ai"],
    "key_obligations": [
        "Licensed financial institutions must develop a board-approved AI strategy",
        "AI risk assessment required before deploying any AI system",
        "High-risk AI systems require explicit pre-approval from QCB",
        "Human oversight protocols must be in place for all AI-assisted decisions",
        "Annual reporting to QCB on AI system performance and incidents",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "sa-sa-sdaiaaf-2024",
    "jurisdiction": "Saudi Arabia",
    "jurisdiction_type": "national",
    "region": "Middle East",
    "country": "Saudi Arabia",
    "short_name": "Saudi Arabia SDAIA AI Adoption Framework 2024",
    "full_name": "Artificial Intelligence Adoption Framework: Maturity Model and Risk Classification",
    "instrument_type": "guidelines",
    "bill_number": None,
    "enacted_date": "2024-09-01",
    "effective_date": "2024-09-01",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p({
        "risk_classification_system": True,
        "impact_assessment_required": True,
    }),
    "enforcement_body": ["Saudi Data and AI Authority (SDAIA)", "National Center for AI (NCAI)"],
    "max_penalty": "Non-compliance with SDAIA guidance may trigger sector-specific regulatory action",
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "civil_law",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://sdaia.gov.sa/en/SDAIA/about/Pages/RegulationsAndPolicies.aspx",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Saudi Arabia's SDAIA AI Adoption Framework, published September 2024, establishes a maturity model and risk-based classification system for AI adoption across government and the private sector. Introduces a four-tier risk classification (low, limited, high, unacceptable) aligned with OECD and EU AI Act principles. Binding for all government entities and referenced as best practice for private sector. Specifies mandatory conformity assessments, transparency requirements, and human oversight obligations for high-risk AI. Accompanied by SDAIA's Generative AI Guideline for public and private use.",
    "notable": "Positions Saudi Arabia as having one of the most structured AI governance frameworks in the GCC. Complements Saudi Vision 2030's AI investment priorities.",
    "legal_citation": "SDAIA AI Adoption Framework: Maturity Model and Risk Classification, SDAIA / NCAI, September 2024.",
    "topics": ["Saudi Arabia AI governance", "SDAIA AI framework", "Gulf AI regulation", "Saudi Vision 2030 AI"],
    "sector_tags": ["all_sectors", "government_services"],
    "technology_tags": ["general_ai", "generative_ai"],
    "key_obligations": [
        "Government entities must conduct AI maturity assessments and classify AI systems by risk tier",
        "High-risk AI systems require conformity assessment before government deployment",
        "Mandatory human oversight mechanisms for Tier 3 (high-risk) AI applications",
        "AI transparency disclosures required for all citizen-facing government AI systems",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "ae-ae-aicharterter-2024",
    "jurisdiction": "UAE",
    "jurisdiction_type": "national",
    "region": "Middle East",
    "country": "United Arab Emirates",
    "short_name": "UAE AI Charter 2024",
    "full_name": "UAE Charter for the Development and Use of Artificial Intelligence",
    "instrument_type": "policy_framework",
    "bill_number": None,
    "enacted_date": "2024-07-30",
    "effective_date": "2024-07-30",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p(),
    "enforcement_body": ["UAE Office of AI (under Ministry of State for AI)", "UAE Government Data and AI Authority (GDAIA)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "civil_law",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://uaelegislation.gov.ae/en/policy/details/the-uae-charter-for-the-development-and-use-of-artificial-intelligence",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "A 12-principle ethical charter issued by the UAE federal government on July 30, 2024, establishing values and principles for responsible AI development and use across the UAE. Covers human dignity, fairness, transparency, accountability, privacy, safety, sustainability, and international cooperation. Non-binding but issued with Cabinet-level endorsement; functions as the national AI ethical compass guiding sector regulation. Distinct from the DIFC and ADGM jurisdictional frameworks.",
    "notable": "UAE is one of the few countries with a dedicated Minister of State for AI; this charter reflects the government's proactive AI positioning.",
    "legal_citation": "UAE Charter for the Development and Use of AI, UAE Federal Government, July 30, 2024.",
    "topics": ["UAE AI charter", "Gulf AI ethics", "UAE AI governance", "responsible AI Middle East"],
    "sector_tags": ["all_sectors"],
    "technology_tags": ["general_ai"],
    "key_obligations": [
        "Government entities to align AI deployments with the 12 charter principles",
        "GDAIA to publish sector guidance implementing charter principles",
        "Annual reporting on AI governance alignment",
    ],
    "ai_specific": True,
    "instrument_binding": False,
    "text_path": None,
    "operative_dates": None,
},

# ──────────────────────────────────────────────────────────────
# AMERICAS
# ──────────────────────────────────────────────────────────────

{
    "id": "co-co-conpes4144-2025",
    "jurisdiction": "Colombia",
    "jurisdiction_type": "national",
    "region": "Americas",
    "country": "Colombia",
    "short_name": "Colombia CONPES 4144 — National AI Policy",
    "full_name": "CONPES 4144: Política Nacional de Inteligencia Artificial 2024–2030",
    "instrument_type": "policy_framework",
    "bill_number": "CONPES 4144",
    "enacted_date": "2025-02-14",
    "effective_date": "2025-02-14",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p({"risk_classification_system": True}),
    "enforcement_body": ["Ministerio de Ciencia, Tecnología e Innovación (MINCIENCIAS)", "Ministerio de Tecnologías de la Información y las Comunicaciones (MINTIC)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "civil_law",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://colaboracion.dnp.gov.co/CDT/Conpes/Econ%C3%B3micos/4144.pdf",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Colombia's National AI Policy 2024–2030, adopted by the National Council of Economic and Social Policy (CONPES) on February 14, 2025. Allocates COP 479 billion (~USD 117 million) over six years for AI investment. Establishes three axes: responsible and inclusive AI development, AI adoption for economic transformation, and AI governance. CONPES documents carry binding planning force for government entities and define mandatory investment commitments. Includes risk-based AI governance aligned with OECD AI Principles. Colombia's most comprehensive AI policy instrument to date.",
    "notable": "CONPES documents are Colombia's primary binding public policy instrument; this is the operative national AI policy with mandatory budget commitments.",
    "legal_citation": "CONPES 4144: Política Nacional de Inteligencia Artificial, DNP, February 14, 2025.",
    "topics": ["Colombia AI policy", "Latin America AI", "CONPES AI Colombia", "Colombia digital transformation"],
    "sector_tags": ["all_sectors", "government_services"],
    "technology_tags": ["general_ai"],
    "key_obligations": [
        "Government entities must align AI programs with CONPES 4144 goals and investment framework",
        "MINCIENCIAS and MINTIC to establish AI governance standards by 2026",
        "Annual investment tracking and reporting against CONPES commitments",
        "Responsible AI principles to be embedded in public sector AI procurement",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "ar-ar-aaipr161-2023",
    "jurisdiction": "Argentina",
    "jurisdiction_type": "national",
    "region": "Americas",
    "country": "Argentina",
    "short_name": "Argentina AAIP Resolution 161/2023 (AI Transparency Program)",
    "full_name": "Resolución 161/2023: Programa de Transparencia y Protección de Datos Personales en el uso de IA",
    "instrument_type": "regulation",
    "bill_number": "Resolution 161/2023",
    "enacted_date": "2023-09-04",
    "effective_date": "2023-09-04",
    "status": "in_force",
    "superseded_by": None,
    "primary_category": "data_protection",
    "categories": ["data_protection", "general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["developers", "deployers", "government_agencies"],
    "provisions": p({
        "impact_assessment_required": True,
        "ai_interaction_disclosure": True,
        "training_data_disclosure": True,
    }),
    "enforcement_body": ["Agencia de Acceso a la Información Pública (AAIP)"],
    "max_penalty": "Administrative sanctions under Law 25.326 (PDPA) — up to ARS 3 million",
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": None,
    "legal_family": "civil_law",
    "inspired_by": [],
    "influenced": [],
    "official_text_url": "https://www.argentina.gob.ar/aaip/ia-responsable",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Binding administrative resolution issued by Argentina's data protection authority (AAIP) on September 4, 2023, creating a 'Program for Transparency and Personal Data Protection in the Use of AI'. Establishes Argentina's first formal AI governance framework under the 2000 Personal Data Protection Act (PDPA, Law 25.326). Requires entities processing personal data with AI to register AI systems, conduct data protection impact assessments, disclose AI use to affected individuals, and participate in the national AI observatory. Creates an AI Advisory Council and transparency certification mechanism.",
    "notable": "Argentina's first binding AI-specific instrument; issued under existing data protection authority rather than requiring new legislation. A notable regulatory approach for Latin America.",
    "legal_citation": "Resolución AAIP 161/2023, September 4, 2023 (Boletín Oficial de la República Argentina).",
    "topics": ["Argentina AI regulation", "AAIP AI", "Latin America AI governance", "AI transparency Argentina"],
    "sector_tags": ["all_sectors"],
    "technology_tags": ["general_ai", "algorithmic_decision_making"],
    "key_obligations": [
        "Entities using AI to process personal data must register AI systems with AAIP",
        "Mandatory data protection impact assessments for high-risk AI applications",
        "Disclosure to individuals when AI is used in decisions affecting their rights",
        "Participation in AAIP's AI observatory and transparency certification program",
    ],
    "ai_specific": True,
    "instrument_binding": True,
    "text_path": None,
    "operative_dates": None,
},

# ──────────────────────────────────────────────────────────────
# CoE AI Convention signatories (Israel + Uruguay)
# These are recorded as separate national entries, not separate convention records
# ──────────────────────────────────────────────────────────────

{
    "id": "il-il-coei-2024",
    "jurisdiction": "Israel",
    "jurisdiction_type": "national",
    "region": "Middle East",
    "country": "Israel",
    "short_name": "Israel — Signature of CoE AI Convention (CETS 225)",
    "full_name": "Israel Signature of the Council of Europe Framework Convention on AI and Human Rights (CETS 225)",
    "instrument_type": "international_agreement",
    "bill_number": None,
    "enacted_date": "2024-09-05",
    "effective_date": None,
    "status": "proposed",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p({
        "risk_classification_system": True,
        "impact_assessment_required": True,
        "human_review_right": True,
        "prohibited_categories": True,
    }),
    "enforcement_body": ["Government of Israel (national implementation)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": "Not yet ratified as of May 2026; signature is binding on Israel under international law not to act against the Convention's object and purpose, but domestic implementation awaits ratification.",
    "legal_family": "international",
    "inspired_by": ["coe-coe-aiconv-2024"],
    "influenced": [],
    "official_text_url": "https://www.coe.int/en/web/conventions/full-list/-/conventions/treaty/225",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Israel signed the Council of Europe Framework Convention on AI, Human Rights, Democracy, and the Rule of Law (CETS 225) on September 5, 2024, becoming one of the first non-European countries to sign. As a signatory, Israel commits to implementing the Convention's principles — human rights safeguards, democratic oversight, and rule of law requirements for AI — upon ratification. The Convention entered into force in 2025 after receiving the required five ratifications. Israel was among the first Middle Eastern countries to sign an international AI governance treaty.",
    "notable": "First Middle Eastern country to sign CETS 225. Signals Israel's alignment with European AI governance standards despite not being an EU member.",
    "legal_citation": "Signature by Israel of CETS 225, Council of Europe, Vilnius, September 5, 2024.",
    "topics": ["Israel CoE AI convention", "CETS 225 Israel", "international AI treaty Israel", "Middle East AI governance"],
    "sector_tags": ["all_sectors"],
    "technology_tags": ["general_ai"],
    "key_obligations": [
        "Signatory obligation not to act against the Convention's object and purpose prior to ratification",
        "Upon ratification: implement human rights impact assessments for AI systems",
        "Upon ratification: establish national oversight mechanism for high-risk AI",
    ],
    "ai_specific": True,
    "instrument_binding": False,
    "text_path": None,
    "operative_dates": None,
},

{
    "id": "uy-uy-coei-2024",
    "jurisdiction": "Uruguay",
    "jurisdiction_type": "national",
    "region": "Americas",
    "country": "Uruguay",
    "short_name": "Uruguay — Signature of CoE AI Convention (CETS 225)",
    "full_name": "Uruguay Signature of the Council of Europe Framework Convention on AI and Human Rights (CETS 225)",
    "instrument_type": "international_agreement",
    "bill_number": None,
    "enacted_date": "2024-09-05",
    "effective_date": None,
    "status": "proposed",
    "superseded_by": None,
    "primary_category": "general_ai_governance",
    "categories": ["general_ai_governance"],
    "scope": "comprehensive",
    "who_regulated": ["government_agencies", "developers", "deployers"],
    "provisions": p({
        "risk_classification_system": True,
        "impact_assessment_required": True,
        "human_review_right": True,
        "prohibited_categories": True,
    }),
    "enforcement_body": ["Government of Uruguay (national implementation)"],
    "max_penalty": None,
    "max_penalty_usd_approx": None,
    "preemption_status": "n/a",
    "preemption_notes": "Not yet ratified as of May 2026; signature is binding on Uruguay under international law not to act against the Convention's object and purpose, but domestic implementation awaits ratification.",
    "legal_family": "international",
    "inspired_by": ["coe-coe-aiconv-2024"],
    "influenced": [],
    "official_text_url": "https://www.coe.int/en/web/conventions/full-list/-/conventions/treaty/225",
    "summary_url": None,
    "last_verified": TODAY,
    "summary": "Uruguay signed the Council of Europe Framework Convention on AI, Human Rights, Democracy, and the Rule of Law (CETS 225) on September 5, 2024, becoming the first Latin American country to sign an international AI governance treaty. Uruguay's signature reflects its strong data protection tradition (home to one of Latin America's most respected data protection frameworks and the Unidad Reguladora y de Control de Datos Personales, URCDP). As a signatory, Uruguay commits to implementing the Convention's human rights, democratic oversight, and rule of law requirements for AI upon ratification.",
    "notable": "First Latin American country to sign CETS 225 — a significant milestone in the Convention's global reach beyond Europe.",
    "legal_citation": "Signature by Uruguay of CETS 225, Council of Europe, Vilnius, September 5, 2024.",
    "topics": ["Uruguay CoE AI convention", "CETS 225 Latin America", "Uruguay AI governance", "international AI treaty Americas"],
    "sector_tags": ["all_sectors"],
    "technology_tags": ["general_ai"],
    "key_obligations": [
        "Signatory obligation not to act against the Convention's object and purpose prior to ratification",
        "Upon ratification: implement human rights impact assessments for AI systems",
        "Upon ratification: establish national oversight mechanism for high-risk AI",
    ],
    "ai_specific": True,
    "instrument_binding": False,
    "text_path": None,
    "operative_dates": None,
},

]  # end NEW_RECORDS


def main():
    with open(REGS_PATH) as f:
        regs = json.load(f)

    existing_ids = {r['id'] for r in regs}
    added = 0
    skipped = 0

    for rec in NEW_RECORDS:
        if rec['id'] in existing_ids:
            print(f'  SKIP {rec["id"]} (already exists)')
            skipped += 1
        else:
            regs.append(rec)
            existing_ids.add(rec['id'])
            print(f'  ADD  {rec["id"]} — {rec["short_name"]}')
            added += 1

    with open(REGS_PATH, 'w') as f:
        json.dump(regs, f, indent=2, ensure_ascii=False)

    print(f'\nDone: {added} added, {skipped} skipped. Total records: {len(regs)}')


if __name__ == '__main__':
    main()
