// Pre-computed rule embeddings (all-MiniLM-L6-v2, 384 dims).
// Generated by: npm run embed-rules
// After running: commit data/embeddings.json and redeploy.

import rawEmbeddings from '../../data/embeddings.json'

export const embeddings: Record<string, number[]> = rawEmbeddings as Record<string, number[]>
